### ISSUE TITLE
hexo generate 生成的demo 是不可用的 index內容均為空

### ISSUE THREAD

**Issue by flybaozi** [AmazingRise/hugo-theme-diary#1]
❯ hexo generate
INFO  Start processing
INFO  Files loaded in 102 ms
WARN  No layout: 2019/12/16/hello-world/index.html
WARN  No layout: archives/index.html
WARN  No layout: archives/2019/index.html
WARN  No layout: archives/2019/12/index.html
WARN  No layout: index.html
INFO  Generated: atom.xml
INFO  Generated: index.html
INFO  Generated: CNAME
INFO  Generated: archives/index.html
INFO  Generated: scss/journal.scss
INFO  Generated: archives/2019/12/index.html
INFO  Generated: archives/2019/index.html
INFO  Generated: js/journal.js
INFO  Generated: js/loadCSS.js
INFO  Generated: css/journal.css
INFO  Generated: 2019/12/16/hello-world/index.html
INFO  11 files generated in 35 ms

**Comment by AmazingRise** [comment]
现在应该没有问题了8
感谢支持，目前功能不是很完善。
最近一个月有点忙，后续还会有更新！
有什么问题欢迎继续反馈呀~
