### ISSUE TITLE
Question about stopping markdown renderer

### ISSUE THREAD

**Issue by shl-cx** [AmazingRise/hugo-theme-diary#10]
I regret any inconvenience caused to you, I can't find a better way to contact you so I open the issue.

I read your blog about [this usage](https://amazingrise.net/posts/getting-to-know-vue-components/), however, I found my Hugo renderer will omit raw HTML when I practised it.
![image](https://user-images.githubusercontent.com/15688641/77005838-79f2ee80-699c-11ea-816e-cef36fca3844.png)
like this fragment:
![image](https://user-images.githubusercontent.com/15688641/77005504-db668d80-699b-11ea-9959-1c9fbb201876.png)

I am wondering how you do it, made the renderer output raw HTML directly.

I would be very grateful for your support.

**Comment by AmazingRise** [comment]
It's a very interesting issue. In fact, if you don't mind, you can leave a comment under my post, and when I see it I will reply to you as soon as possible. (But without email notification, I'll fix it later.)

OK, let's back to our topic. There are many ways to do this.
1. The best way I think you can intergrate markdown content and raw HTML code is to enable the unsafe feature of markup renderer.
You can add this to your site's `config.toml`
```
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = true
```
Due to safety concerns, renderer disabled this feature by default (keeping away any possible XSS attacks).
2. There are also a way to implement the insertion of raw HTML:
You can directly rename the post from `.md` to `.html`
Hugo can compile HTML files with [frontmatter](https://github.com/AmazingRise/hugo-theme-diary/wiki/Post's-meta-data).
But while using HTML, only HTML code is allowed, no markdown code will be compiled.

**Comment by AmazingRise** [comment]
And another thing I should remind is, this theme is under MIT license.
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
Under MIT license, users have freedom to do many things, but they should reserve the copyright declaration of this theme. :)

**Comment by shl-cx** [comment]
> It's a very interesting issue. In fact, if you don't mind, you can leave a comment under my post, and when I see it I will reply to you as soon as possible. (But you can't receive a email notification, which I'll fix later.)
> 
> OK, let's back to our topic. There are many ways to do this.
> 
> 1. The best way I think you can intergrate markdown content and raw HTML code is to enable the unsafe feature of markup renderer.
>    You can add this to your site's `config.toml`
> 
> ```
> [markup]
>   [markup.goldmark]
>     [markup.goldmark.renderer]
>       hardWraps = false
>       unsafe = true
>       xHTML = true
> ```
> 
> Due to safety concerns, renderer disabled this feature by default (keeping away any possible XSS attacks).
> 2. There are also a way to implement the insertion of raw HTML:
> You can directly rename the post from `.md` to `.html`
> Hugo can compile HTML files with [frontmatter](https://github.com/AmazingRise/hugo-theme-diary/wiki/Post's-meta-data).
> But while using HTML, only HTML code is allowed, no markdown code will be compiled.

Thanks for your help, I was thinking of a Tag Plugins solution like Hexo.

One more thing is the favicon params can be mentioned in wiki, for `head.html`
```
{{ if .Site.Params.favicon }}
<link rel="icon" href="{{ .Site.Params.favicon }}">
<!-- favicon -->
```
As for the pages should be distinguished from posts, in my humble opinion, pages won't be shown in homepage, I took a simple way to practise this function by adding a param named hide :
```
        {{range .Paginator.Pages}}
        {{$hidePage := .Params.hide}}
        {{if $hidePage}}
        {{else}}
            {{if and (.IsPage) (.Params.date)}}
```
Of course, there is another way to practise better, like using something like `{{ range }}` that I am not familiar with.

I suppose it would be cool that the theme will add the searching function like using ajax live search, maybe in the feature?

**Comment by shl-cx** [comment]
> And another thing I should remind is, this theme is under MIT license.
> 
> > The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
> 
> Under MIT license, users have freedom to do many things, but they should reserve the copyright declaration of this theme. :)

In fact, I do keep the copyright declaration of this theme, but not as a _substantial portions_ way.
For the developing convenience, I tested my features by commenting out all the original parts of the footer. I'd like to add the copyright declaration in the near future.

![image](https://user-images.githubusercontent.com/15688641/77054680-06d49100-6a0b-11ea-9f79-50945201c146.png)

**Comment by shl-cx** [comment]
> And another thing I should remind is, this theme is under MIT license.
> 
> > The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
> 
> Under MIT license, users have freedom to do many things, but they should reserve the copyright declaration of this theme. :)

In fact, I do keep the copyright declaration of this theme, but not as a _substantial portions_ way.
For the developing convenience, I tested my features by commenting out all the original parts of the footer. I'd like to add the copyright declaration in the near future.

![image](https://user-images.githubusercontent.com/15688641/77054680-06d49100-6a0b-11ea-9f79-50945201c146.png)

**Comment by AmazingRise** [comment]
Thanks for your support.
