### ISSUE TITLE
Org-mode result block in dark mode has some problems

### ISSUE THREAD

**Issue by ixnij** [AmazingRise/hugo-theme-diary#101]
**Describe the bug**
在黑暗模式下，Org-mode 的 RESULT 块变成了黑色，完全不可读。

**SnapShot**

<img width="721" alt="截屏2021-09-05 下午7 07 35" src="https://user-images.githubusercontent.com/61684794/132124590-7d70d19c-06cf-462b-86b7-64ea3c8640ec.png">
<img width="721" alt="截屏2021-09-05 下午7 07 27" src="https://user-images.githubusercontent.com/61684794/132124592-e2890ebf-a4d5-4c7c-b1d3-669320dc963d.png">

**Environment**

```console
wu@ThomasdeMacBook-Pro ~ % hugo version
hugo v0.88.1+extended darwin/arm64 BuildDate=unknown
```

Browser:
Apple Safari 版本14.1.2 (16611.3.10.1.6)

**Comment by AmazingRise** [comment]
Hi, ixnij
你说的 org-mode 是怎么插入的
是通过 ` ``` ``` ` 插入的吗？

**Comment by ixnij** [comment]
> Hi, ixnij
> 你说的 org-mode 是怎么插入的
> 是通过 `` ``` ``` `` 插入的吗？

不是的，下面的结果块是 Emacs 生成的。

是这样的：

```org
#+BEGIN_SRC scheme
(define x 4)
#+END_SRC
```

在 Emacs 中按下 <kbd>C-c C-c</kbd> ，会自动出现这段代码执行的结果，也就是会在这个代码块的后面插入 RESULT 块，效果是这样的:

```org
#+RESULTS:
: t
```

**Comment by AmazingRise** [comment]
我尝试修了一下，最新的代码在 testing 分支里，你可以看一下。

这是我测试的：

```
Evaluated results
#+BEGIN_SRC scheme
(define x 4)
#+END_SRC

#+RESULTS:
: t
```

这是测试结果：

![image](https://user-images.githubusercontent.com/8315221/133883765-a27862fe-260d-4613-827b-118b7d05f5fd.png)

**Comment by ixnij** [comment]
好的，这样子的效果就很棒了！谢谢！
