### ISSUE TITLE
Waline 无法显示评论

### ISSUE THREAD

**Issue by jwhj** [AmazingRise/hugo-theme-diary#102]
**Describe the bug**
当至少有一条评论时，waline无法显示评论。

**To Reproduce**
按照wiki部署好waline，在任意一条post下发表一条评论。

**Expected behavior**
评论正常显示

**Screenshots**
评论无法显示
![image](https://user-images.githubusercontent.com/9743928/133960948-760aa2f7-f51c-403f-85d8-c8216ffadb52.png)
控制台的错误信息
![image](https://user-images.githubusercontent.com/9743928/133961032-beb2f0bc-fb21-4394-b15e-485671c04dd9.png)

**Environment**
Hugo Static Site Generator v0.74.3 windows/amd64 BuildDate: unknown
Microsoft Edge 93.0.961.47

**Comment by AmazingRise** [comment]
Hi, jwhj
能说一下这个问题是怎么复现的吗？我这里完全正常。

**Comment by jwhj** [comment]
我检查了一下，在config.toml的[params]里面加上enableLaTeX=true之后，才能复现。

**Comment by AmazingRise** [comment]
感谢反馈，我已经修复好了，在我这测试是没有问题的。
最新的代码在 testing 分支里。
你那边如果没有问题的话就关闭这个 issue 吧！
