### ISSUE TITLE
[Feature Request] Background image/wallpaper?

### ISSUE THREAD

**Issue by Darthagnon** [AmazingRise/hugo-theme-diary#103]
A very beautiful theme you have made! Thank you!

I was wondering, is there any way to add an optional background image? (or separate left and right background images?) 

- On Desktop, it would be nice to add a splash of colour either side of the main central view...
- On mobile, perhaps the images could be in the header area, behind the blog title, and/or in the sidebar flyout
- Perhaps multiple images? One for light theme, one for dark theme, or possibly a list that displays different light/dark images depending on the date (good for holidays, Christmas, etc.)

**Comment by AmazingRise** [comment]
Hi, Darthagnon
It's easy to implement the feature by modifying `document.body.style.background` via JavaScript.
As for the last point, it's a really good idea, but it may also be hard for user to configure. From the aspect of user-friendliness, it may not appear in the final version.

Thanks for your suggestions! I'll implement it someday.

**Comment by Darthagnon** [comment]
For point 3, I've started work on some JS to do that in a private repo. Thank you for the info on how to change the background!

**Comment by AmazingRise** [comment]
OK, now I'll close this issue. Thanks for your support!

**Comment by Darthagnon** [comment]
@AmazingRise 

I'm trying to change the background/wallpaper, but I'm not having any luck. Any chance you could give me a pointer where to put the code?

I'm trying the following. I've tried putting it in `layouts\index.html` and 'layouts\partials\head.html` without success.
```
<script type="text/javascript">
	function wallpaper() {
		document.body.style.background = "red";
	}
	console.log("Wallpaper not working");
</script>
```

**Comment by Darthagnon** [comment]
Thank you!!!

```
<script>
	function wallpaper() {
		document.body.style.backgroundColor = "red";
	}
	wallpaper();
	console.log("Wallpaper working!");
</script>
```

I'll try and get a nice adaptive (and optional) wallpaper parameter set up, will open a PR once I've succeeded. I set up a website for a friend's podcast using Diary ([dragonsnotincluded.github.io](https://dragonsnotincluded.github.io/)), and set up some shortcodes I'll be using last night [here](https://github.com/Darthagnon/darths-hugo-shortcodes)

**Comment by AmazingRise** [comment]
I think using embedded stylesheet in HTML is better than this solution, such as:
```html
<style>
body {
    background-image: {{ .Site.Params.your_variable_name }};
}
</style>
```

**Comment by Darthagnon** [comment]
Currently testing both, and feeling like an idiot, as I'm sure it's something simple I've overlooked.
```
<style type="text/css">
	body {
		background-image: "{{ .Site.Params.customWallpaper | absURL }}";
	}
</style>
```
and 
```
<script type="text/javascript">
	function wallpaper() {
		document.body.style.background = "{{ .Site.Params.customWallpaper | absURL }}";
	}
	wallpaper();
	console.log("Wallpaper working!");
</script>
```
JS version works with colours, but annoyingly, both mess up the url forward-slash `/` and backslash `\`,
When supplied with `/img/customWallpaper.png`, CSS version gives:
`http\3a\2f\2flocalhost\3a 1313\2fimg\2f customWallpaper.png`
and JS version gives:
`http:\/\/localhost:1313\/img\/customWallpaper.png`

**Comment by AmazingRise** [comment]
> JS version works with colours

You can use `background` instead of `background-image` to let it works with colors, e.g.:

```css
<style>
body {
    background: {{ .Site.Params.your_variable_name }};
}
</style>
```

The `style` attribute of JS is equivalent to those in CSS. Just needed to do some lexical transform, like `backgroundImage` to `background-image`.
