### ISSUE TITLE
Feature Request: Giscus

### ISSUE THREAD

**Issue by ChungZH** [AmazingRise/hugo-theme-diary#104]
A comments system powered by **GitHub Discussions**. :octocat: 💬 💎

https://github.com/giscus/giscus https://giscus.app/

**Comment by AmazingRise** [comment]
Hi, old friend
There is too many configurations in Giscus. 🤣
If anyone wants to add it into Theme Diary, you can edit `layouts/partials/comment.html` by yourselves for a temporary solution.

(Being so busy these days)

Thanks for your support.

**Comment by Darthagnon** [comment]
It's "heavily inspired by [utterances](https://github.com/utterance/utterances)" - Hugo theme [Dream](https://github.com/g1eny0ung/hugo-theme-dream) (I use a [fork](https://github.com/Darthagnon/hugo-theme-dream) on my website) uses utterances, maybe it could be ported.

**Comment by shinyzhu** [comment]
I've added giscuss and you can find it on my blog. Please review #140

**Comment by shinyzhu** [comment]
> It's "heavily inspired by [utterances](https://github.com/utterance/utterances)" - Hugo theme [Dream](https://github.com/g1eny0ung/hugo-theme-dream) (I use a [fork](https://github.com/Darthagnon/hugo-theme-dream) on my website) uses utterances, maybe it could be ported.

That's true.

But I'd prefer **Discussions** for comments rather than **Issues**.

**Comment by AmazingRise** [comment]
Pull Request #140 solved this issue.
And later I'll make it compatible with dark theme switch.

**Comment by AmazingRise** [comment]
> Pull Request #140 solved this issue. And later I'll make it compatible with dark theme switch.

Dark mode adapted in https://github.com/AmazingRise/hugo-theme-diary/commit/52c4be12d3f88a260a0de8b166f6c99e64061a15
