### ISSUE TITLE
Twikoo不支持部署在vercel吗

### ISSUE THREAD

**Issue by SenLief** [AmazingRise/hugo-theme-diary#117]
一直配置不对，是我的配置问题，还是说不支持的？
环境id的样式是什么样的呢?

**Comment by AmazingRise** [comment]
Hi SenLief
这个可能得参照一下 Twikoo 那边的文档
主题这里做的只是引用他们提供的 JS

**Comment by SenLief** [comment]
好的，我再试一下，这个ID一直不对，不知道什么原因。

**Comment by SenLief** [comment]
Hi
查看了一下Twikoo的issue，貌似是因为版本低的问题。现在用的是1.3.0的版本，我用1.5.0的版本试了一下是可以的。
您看下可以修改下版本嘛？

**Comment by SenLief** [comment]
最新的版本为1.5.3

**Comment by AmazingRise** [comment]
好的 我有空更一下
