### ISSUE TITLE
主页配置成按发布时间排序

### ISSUE THREAD

**Issue by SenLief** [AmazingRise/hugo-theme-diary#118]
我现在发布的会安装字母排序？请问如何配置成按发布时间排序的？

**Comment by AmazingRise** [comment]
Hi SenLief
看了一下你的博客，https://senlief.xyz/posts/
你的文章中没有配置正确的日期，所有的文章的日期都显示为4月11日。
建议阅读一下 Hugo 的文档。

Thanks

**Comment by SenLief** [comment]
不好意思我的问题，忘记更新后台代码了。
