### ISSUE TITLE
allow for nested menues, feature request

### ISSUE THREAD

**Issue by bmaeser** [AmazingRise/hugo-theme-diary#12]
hi rise,

thanks a lot for this hugo theme, its great!

i am currently prepairing a website with cooking-recipies for (self) quarantined people because of the covid-19 pandemic, and i will use your theme to do so.

would it be possible to allow for nesting in the main menue?

so this would be possible:

- home
- recipies
  - categories
  - ingredients
- rss-feed

thank a lot in advance,
bernhard

**Comment by AmazingRise** [comment]
Thanks for your issue. The COVID-19 really influenced a lot. I'm very honored that my theme would help you to help those people. :)
Let's back to our main topic.

First, let's introduce some terms:
1. `recipies` is a `section` of Hugo blog.
2. `categories` and `ingredients` are `taxonomies` of a blog.

So this feature request can be described as: to implement a `taxonomy` under each `section`.
(The original behaviour of taxonomy page is to show all the things, whichever the `section` they belong to.)

Furst, I found [a solution to do this](https://discourse.gohugo.io/t/taxonomies-per-section/18423/5) on Hugo forum (see madipse's reply). And this solution needs some modifications to `single.html`. An annoying point is: if you have some other contents before, they needs to be modified, too.

I think there is a better practice.

GitHub pages enables you to set up a site under every project repositories. (if you have a repo named `recipes`, and add a branch `gh-pages`. Then upload some webpages, you will get a sub-site: https://your-github-name.github.io/recipes)

You can establish a seperate site for these recipes. In this way, you need to:
- Set up a sub-site.(For details, you can see [this link](https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).)
- Rename the default "contents/posts" folder to "contents/recipes"
- Add two `taxonomies` in `config.toml`: `categories` and `ingredients`.
- To classify these contents, you can declare in the `frontmatter` of each post, for example:
```yaml
---
title: "An example recipe"
date: 2018-03-18T12:13:32+05:30
description: "This is an example recipe."
ingredients: ["tomato","potato","cheese"]
categories: "simple foods"
---
```
This solution may also need some small modifications to `single.html`.(To replace `tags` with `ingredients`) It's easier to do, comparing with the first solution.
If you'd like this solution, tell me and i will open a branch to do these small modifications.

Welcome other ideas on this. I'm very glad to help.

**Comment by bmaeser** [comment]
hi, thanks for the fast reply.

it wouldnt even have to be that complex. menu is generated via `[[menu.main]]` entries in config.toml. hugo has support for  [nesting menues](https://gohugo.io/content-management/menus/#nesting), but the theme does not render it, or has css/js to style it.

that would be more than enough
thx

**Comment by AmazingRise** [comment]
> hugo has support for nesting menues, but the theme does not render it, or has css/js to style it.

If you are meaning to render something like this,
```toml
[[menu.main]]
url = "/recipes/categories"
parent = "recipes"
name = "Categories"
weight = 2
```
...and there is only submenu not working in this theme:
I've added support for rendering submenu [in the lastest commit](https://github.com/AmazingRise/hugo-theme-diary/commit/3f4ee025012785f484a9eee1d0b4ebd43846e749).
Also adapted for mobile view.
Now, the menu with children items is expandable on sidebar. When click on it, the list will expand, you will see items in it.

And please reply to me if any further things needs to be added. (It's the first time for me to use this feature, not familiar to me.)
Thanks. :)

**Comment by AmazingRise** [comment]
Hi bmaeser,
Could you give me some feedback on this function since [this commit](https://github.com/AmazingRise/hugo-theme-diary/commit/3f4ee025012785f484a9eee1d0b4ebd43846e749)?
I think this function is ready to use.
If no further modifications needed, i'll close this issue. :)
Thanks.

**Comment by bangcool** [comment]
你好，Rise！感谢你提供的 Hugo 主题，很喜欢它的简约、实用以及中英文显示都很不错，主题配置也很方便。在使用的过程中，没有找到关于站内搜索功能的。如果可以的话，期望在以后的版本中能增加这一功能。最后，再一次谢谢 Rise 分享！

**Comment by AmazingRise** [comment]
> 你好，Rise！感谢你提供的 Hugo 主题，很喜欢它的简约、实用以及中英文显示都很不错，主题配置也很方便。在使用的过程中，没有找到关于站内搜索功能的。如果可以的话，期望在以后的版本中能增加这一功能。最后，再一次谢谢 Rise 分享！

关于这个问题：https://github.com/AmazingRise/hugo-theme-diary/issues/16

感谢你的支持，但是请不要在其他人的 issue 下面发表无关内容。如果有新的功能或建议，请另发 issue，并且建议在提出问题之前翻阅 wiki 和 issues。谢谢合作。

Please do not post unrelated questions under other issues. Thanks for cooperation.

**Comment by bmaeser** [comment]
i am so very sorry, i had to abandon the project for lack of time and forgot about it.

it seams to work just fine, thank you very much for this.
sorry for the late feedback.
