### ISSUE TITLE
Custom Sidebar: About is rendered in main page

### ISSUE THREAD

**Issue by Darthagnon** [AmazingRise/hugo-theme-diary#127]
**Describe the bug**

About page, which is listed outside of `/posts/`, is listed with posts on the homepage. No idea how to exclude it; moving to different directories and adjusting paths reindexes it, back to the homepage. `private: true` front matter does nothing ([this theme implements this to avoid indexing certain pages](https://www.axiomtheme.com/docs/frontmatter/))

**To Reproduce**
`[site root]/content/about.md` = About page

`[site root]/content/posts/` = main posts/content

custom sidebar entry:
```
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[[menu.main]]
url = "/about"
name = "About us"
weight = 4
```

**Expected behavior**
About should only appear under the About Us sidebar entry, and nowhere else.

**What actually happens**
About appears under the sidebar entry, and on the homepage (but is excluded from Archive).

## Question
Is there a way to set the homepage to display `[site root]/content/posts/`, rather than everything within `/content/`?

Alternatively, is there a way to exclude certain pages from being listed anywhere on the site?

If so, might be worth adding to the Wiki, under customising the sidebar.

**Comment by AmazingRise** [comment]
Hi Darthagnon
Thanks for your feedback. I'll add this feature later.
(Too busy in these days)

**Comment by Darthagnon** [comment]
I've been learning a lot about Hugo; if I get a chance, I'll try implementing and pull request, too

**Comment by shinyzhu** [comment]
This really matters. 

I don't want to include `about` page in list. And I don't like there are `previous` and `next` links. I also need `date` and `lastmod` in the `about` page. :)

I'm still learning Hugo.

**Comment by AmazingRise** [comment]
Solved in https://github.com/AmazingRise/hugo-theme-diary/commit/95ab2b1dfcef80ef43414a249e59a149a5a6868d

Adding `hidden: true` in a post, and it will be hidden in your homepage.
