### ISSUE TITLE
更新hugo版本后代码高亮默认字体显示为黑色

### ISSUE THREAD

**Issue by trustywolf** [AmazingRise/hugo-theme-diary#128]
**Describe the bug**
hugo 0.92.2及之前版本代码高亮默认字体颜色正常显示，0.93.0及之后版本高亮默认字体变为纯黑色

**To Reproduce**
- 跟随官方[Quick Start](https://gohugo.io/getting-started/quick-start/)新建测试用site和post
- 在post添加代码块

**Expected behavior**
代码高亮默认字体颜色

**Screenshots**
![image](https://user-images.githubusercontent.com/18548903/176710799-74862851-efc6-4483-98d0-4aded6007072.png)

**Environment**
Your Hugo version, generated from `hugo version`.
`hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio`
Firefox & Chrome

**Comment by AmazingRise** [comment]
Thanks for your contribution. Your pull request has been merged.
