### ISSUE TITLE
Adjusting the opacity of side bar's theme color

### ISSUE THREAD

**Issue by Oyyko** [AmazingRise/hugo-theme-diary#131]
如题。因为觉得页面的主题色显示的比较淡。即使设为#000000这种纯黑，也还是很淡。。

**Comment by Oyyko** [comment]
补充：我说的是博客名区域的背景高亮，颜色很淡

**Comment by Oyyko** [comment]
在journal.scss中应该有相关字段可以调节。但我不太熟悉前端。。不知道具体应该是哪一个

**Comment by AmazingRise** [comment]
Hi Oyyko
This line may helps.
https://github.com/AmazingRise/hugo-theme-diary/blob/bc2908bd710e0f35ea10184b5badf9205c34a35c/assets/scss/journal.scss#L437

By increasing the number, a deeper color will be applied.

**Comment by Oyyko** [comment]
Thanks! It really helps.
