### ISSUE TITLE
Can homepage posts list sort by 'lastmod' instead of 'date'?

### ISSUE THREAD

**Issue by lin5464** [AmazingRise/hugo-theme-diary#136]
Currently posts list on home page sort by the order of  front matter 'date', how can i get it sort by front matter 'lastmod'?
Thanks in advance.

**Comment by AmazingRise** [comment]
Hi lin5464
You can refer to this.
https://gohugo.io/templates/lists/#by-last-modified-date

Thanks for your support.

**Comment by AmazingRise** [comment]
Closed due to inactivity.
