### ISSUE TITLE
The dividing line moves left and right.

### ISSUE THREAD

**Issue by Oyyko** [AmazingRise/hugo-theme-diary#137]
**Describe the bug**

The dividing line moves left and right when switching between screens with and without text. And in other cases.

For example, at your website https://risehere.net/, when I switched between 分类 and 关于, the dividing line will move.

The dividing line is the line that separates the column on the left from the text on the right.

**To Reproduce**
Steps to reproduce the behavior.

Switch between different views. For example, switch between [posts](https://risehere.net/posts/) and [categories](https://risehere.net/categories/)

**Expected behavior**

The line should not move.

**Screenshots**

**Environment**
Your Hugo version, generated from `hugo version`.
(OS information also included in hugo version, so you don't need to tell this.)
And your browser's basic information.

**Additional context**

**Comment by AmazingRise** [comment]
Hi Oyyko,
The scroll bar on the right caused this problem. Here is a temporary fix:

Add these into `assets/scss/journal.scss`:
```
body {
  scrollbar-width: none; // Firefox
}
::-webkit-scrollbar {
  display: none; // Chrome, Safari, Edge
}
```

To fix this issue permanently, current layout and style should be refactored. It's not a short term job, and I'll continuously work on this. The refactor will be the next milestone of this project.
