### ISSUE TITLE
How do you add images to the categories?

### ISSUE THREAD

**Issue by babadoctor** [AmazingRise/hugo-theme-diary#141]
I really love pic related images next to the post title as below
![1](https://user-images.githubusercontent.com/8715318/215973039-971ddd84-dac9-4075-80bd-b79380673b48.jpg)
How can I make it so that when I click on categories (and a specific category) it shows the featured image next to the post titles?
I don't want it to ever not see the image next to it
![2](https://user-images.githubusercontent.com/8715318/215973220-8ff049f8-bcf2-4849-9977-ba6faed6a810.jpg)

I know how to add the normal image, but I don't know how to make it show up everywhere.
Pic related is my use case:
![image](https://user-images.githubusercontent.com/8715318/215973508-cca201f3-06ea-47be-9824-a069fa843110.png)

![image](https://user-images.githubusercontent.com/8715318/215973667-b813df50-f98c-4391-a332-09e45a28671b.png)

I would like the image next to the name above.

**Comment by AmazingRise** [comment]
Hi, babadoctor

You can replace some lines in `taxonomy.html` with those in `index.html` to make pics show up everywhere.

Here is the **instruction**:

Replace these lines in `layouts/_default/taxonomy.html`:
![image](https://user-images.githubusercontent.com/8315221/215974165-2f3f35d5-2700-4f5d-9922-65796978ec93.png)

with these lines in `layouts/index.html`:
![image](https://user-images.githubusercontent.com/8315221/215974305-47dc0f39-b70c-4d19-a191-468fa70b3d67.png)

**Comment by babadoctor** [comment]
Hmm, that didn't seem to work.

See my taxonomy.html file below:
![image](https://user-images.githubusercontent.com/8715318/215975543-8b9658e8-acea-4ef6-85a1-f8fd598e7644.png)

**Comment by AmazingRise** [comment]
It works for me here. Have you saved the file, or did you open the blog locally (usually https://localhost:1313/) rather than the online version?
![image](https://user-images.githubusercontent.com/8315221/215976070-c2d6ff40-54d6-41cc-9dec-94607f02a039.png)
![image](https://user-images.githubusercontent.com/8315221/215976215-d4704e0b-b03f-4822-accb-834e881450f8.png)

**Comment by babadoctor** [comment]
It works only on the specific taxonomy name "categories" which is fine ( I wanted this too)
![image](https://user-images.githubusercontent.com/8715318/215982696-91b007c1-c74b-4dfd-a705-dc86b207465a.png)

However, I would like to have the image show up when I am in this section as well
![image](https://user-images.githubusercontent.com/8715318/215982830-5e2cf6df-ba48-4b99-816e-0e4b820cce1d.png)

Here is my TOML file

![image](https://user-images.githubusercontent.com/8715318/215982947-befa8936-0e97-48e8-9f7a-3f39164423d1.png)

**Comment by AmazingRise** [comment]
Oh, I see. The latter one is called `section` in Hugo.
In `layouts/_default/section.html`, replace Line 17-28 as you did in `taxonomy.html`.
Then the pics should show up.

**Comment by babadoctor** [comment]
> Oh, I see. The latter one is called `section` in Hugo. In [`layouts/_default/section.html`](https://github.com/AmazingRise/hugo-theme-diary/blob/95ab2b1dfcef80ef43414a249e59a149a5a6868d/layouts/_default/section.html#L17), replace Line 17-28 as you did in `taxonomy.html`. Then the pics should show up.

It works perfectly. Thank you. And thank you for your theme, it's my favorite hugo theme :)
