### ISSUE TITLE
Question about adding an author for posts

### ISSUE THREAD

**Issue by babadoctor** [AmazingRise/hugo-theme-diary#143]
How can I add an author label to posts, which can be added by editing the front matter of a webpage?
See attached pictures for what I had in mind.
<img width="374" alt="author3" src="https://user-images.githubusercontent.com/8715318/217413994-46f85e6a-98b0-43e8-b1c4-1fa9ff6d84a4.png">
<img width="564" alt="author 2" src="https://user-images.githubusercontent.com/8715318/217414422-ce3677ff-ffa2-41ac-aa5e-dd82c181761d.png">
<img width="701" alt="author1" src="https://user-images.githubusercontent.com/8715318/217414470-be6fb03b-ec3c-410a-a09d-08e4e245f5ff.png">

Thank you

**Comment by AmazingRise** [comment]
Hi babadoctor,

You can add `{{ .Params.author }}` to:

https://github.com/AmazingRise/hugo-theme-diary/blob/bad0d28ed269fe2d7ea3c6e252dbaedc8fd4c74e/layouts/_default/single.html#L75

and

https://github.com/AmazingRise/hugo-theme-diary/blob/bad0d28ed269fe2d7ea3c6e252dbaedc8fd4c74e/layouts/_default/single.html#L28

Later I'd consider to introduce this feature. Thanks for your advice.

**Comment by babadoctor** [comment]
Hi Rise,

Adding  {{ .Params.author }} to line 75 worked in adding the author to the bottom of each page, but for some reason adding it to line 28 did not add it to the post meta.

This is what my code looks like
![image](https://user-images.githubusercontent.com/8715318/217674222-1ac4f849-fd72-40e0-814c-a09ac5435de8.png)

**Comment by AmazingRise** [comment]
It works for me.
![image](https://user-images.githubusercontent.com/8315221/217789642-967c28ad-5544-4575-ab3d-0a608d09ff2c.png)
![image](https://user-images.githubusercontent.com/8315221/217789736-0e4cc870-5bcd-4f10-84a6-f6843e7fd6ae.png)

**Comment by babadoctor** [comment]
I'm not sure what i'm doing wrong.

Could it be related to the fact I have the images here... ?
![image](https://user-images.githubusercontent.com/8715318/218287524-8bcd4123-1bbb-4230-93a2-9eaa090b7afa.png)
