### ISSUE TITLE
是否可以考虑使用此字体

### ISSUE THREAD

**Issue by aaronuu** [AmazingRise/hugo-theme-diary#144]
https://atelier-anchor.com/typefaces/smiley-sans

**Comment by AmazingRise** [comment]
Hi, aaronuu

感谢反馈。目前可以尝试修改`layouts/partials/head.html`及`assets/scss`以应用自定义字体。

不过我还是想多说两句。这个主题的远古版本是有[自定义字体](https://github.com/AmazingRise/hugo-theme-diary/wiki/Customization/4f5f7d3e3b821b8e5dc2a70673f2053e4f819a69#change-default-font-scheme)配置的。但出于以下几个原因我去掉了这个特性：

1. 在加载字体期间，整个网页和对应的文本可能会出现闪烁的现象。可以通过异步加载CSS，以及应用[font-display的swap属性](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display)来解决这个问题。
2. 中文字体文件普遍较大，动辄几兆甚至几十兆（英文字体因为体积较小不存在这个问题）。有[一些方法](https://web.dev/i18n/zh/optimize-webfont-loading/)可以通过加载字体子集的方式以减少流量传输。[Google Fonts API](https://developers.google.com/fonts/docs/getting_started) 在这方面做的比较好。
3. 在文本量大的时候，2中所提到的解决方案也有缺陷：在字体未加载全的时候，有的字是系统默认字体，有的应用了所需的字体，会一个字大一个字小的情况。随着字体的加载，这些字会逐个变大，观感不是很好。**在文本量少的时候这个问题不明显。**

如果仍有其它问题，欢迎反馈。
