### ISSUE TITLE
夜间模式下看不见表格内容

### ISSUE THREAD

**Issue by wwng2333** [AmazingRise/hugo-theme-diary#145]
如题，表格底色与字的颜色一致，导致奇数行的内容都看不见。
```md
|p值|描述|
|---|----|
|p601|posLimit|
|p602|iPos|
|p603|ePos|
|p604|automation|
|p605|autohitBuy|
|p606|autohitSell|
```
如下图所示：
![image](https://user-images.githubusercontent.com/17147265/219478617-0223468d-32ab-435b-be33-f2f5f772dd04.png)

**Comment by AmazingRise** [comment]
Hi wwng2333
感谢你的反馈。我发现你的博客很多地方的样式都怪怪的。
查了源代码后发现你好像自己引用了一个bootstrap.min.css，将原有的样式覆盖掉了。
```html
<link crossorigin=anonymous integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA==" href=https://lib.baomitu.com/twitter-bootstrap/5.2.3/css/bootstrap.min.css rel=stylesheet>
```
将baomitu.com的这些css去掉之后再看看样式是否回归正常？
如有问题欢迎继续反馈。

**Comment by wwng2333** [comment]
Thanks, 删掉以后一切正常
