### ISSUE TITLE
images not displaying

### ISSUE THREAD

**Issue by goeldicom** [AmazingRise/hugo-theme-diary#146]
**Describe the bug**
images are not displaying

**To Reproduce**
`image.png` is uploaded to the top `/images` directory.
In a post both lines `images = image.png` and also `featured_image = image.png` exist.
Also tried it with `images/image.png` or `/mydiaryname/images/image.png`

**Expected behavior**
Image is displayed on list of posts and also inside of the post as background.

**Environment**
0.101.0 / Chrome 110.0.5481.177 / Firefox 110.0.1

**Comment by shinyzhu** [comment]
The **TOP** `/images` in this repo? I think it's used for storing screenshots of this theme :)

You can put them under `/static/images` so that can be built to the output `/images` folder.
Then you can use this in the frontmatter:
```
featured_image: "/images/image.png"
```

Hope it works.

**Comment by AmazingRise** [comment]
Hi @goeldicom ,
shinyzhu's solution should work.
Here is another way to refer static resources, page bundles(https://gohugo.io/content-management/page-bundles/#branch-bundles). You can put the image alongside with the post, and then you can directly refer it in its frontmatter.

Please read Hugo documentation for more details. Thanks for your feedback.
