### ISSUE TITLE
Single quote is replaced with &rsquo;

### ISSUE THREAD

**Issue by wwng2333** [AmazingRise/hugo-theme-diary#151]
如题，我使用katex渲染公式，类似
```markdown
$$ f'(0)=\lim_{x \to 0}\frac{f(x)-f(0)}{x-0},x=0 $$ 
```
vscode里面预览正常，hugo生成以后变成了中文引号。
测试地址：https://blog.csgo.ovh/posts/114-mathematical-formula
请作者大佬帮我排查一下是不是主题的问题，谢谢！

**Comment by AmazingRise** [comment]
Hi wwng2333
感谢反馈
等我过两天有空排查一下

**Comment by AmazingRise** [comment]
Hi wwng2333
Please add a backslash before the single quote.
```markdown
$$ f\'(0)=\lim_{x \to 0}\frac{f(x)-f(0)}{x-0},x=0 $$
```

![image](https://github.com/AmazingRise/hugo-theme-diary/assets/8315221/f472347c-c77e-41e2-9429-d5c3042d30ac)

Thanks for your feedback.

**Comment by wwng2333** [comment]
it works on single ', but doubule ' not work.
```latex
$$ f''(x)=[f(x)]',x\ne0 $$
```

**Comment by AmazingRise** [comment]
Try `\'\'`?

**Comment by wwng2333** [comment]
> Try `\'\'`?

`ParseError: KaTeX parse error: Got function '\'' with no arguments as argument to '\'' at position 3: \'\̲'̲·

vscode reported error, but hugo works. Thanks for help!

**Comment by AmazingRise** [comment]
> > Try `\'\'`?
> 
> `ParseError: KaTeX parse error: Got function ''' with no arguments as argument to ''' at position 3: '\̲'̲·
> 
> vscode reported error, but hugo works. Thanks for help!

VSCode's LaTeX preview is based on another Markdown engine, which is different from that of Hugo.
