### ISSUE TITLE
How to add RSS feed? I don't understand where to add rss link.

### ISSUE THREAD

**Issue by babadoctor** [AmazingRise/hugo-theme-diary#152]
I see that in the readme it says that we need to edit themes/hugo-theme-diary/layouts/index.rss.xml in order to add an RSS feed to my website.

Where do we edit this file in order to add a link to an rss feed?

Example: this rss feed... https://pubmed.ncbi.nlm.nih.gov/rss/search/

I edited config.toml in order to add a category to [[main]], but all I get when accessing the page is a white page.

Thank you

**Comment by AmazingRise** [comment]
Hi babadoctor
RSS page is generated by Hugo. By default, if you visit `https://your_site_base_url/index.xml`, you will see a RSS xml generated by Hugo. (e.g. my blog: https://risehere.net/index.xml)
You can add a link to `index.xml` on the sidebar (by editing config.toml). If someone is interested in your site, he/she can copy the link to his/her own RSS subscriber. Then he/she will get updates from your site.

Please let me know if you have further questions. Thanks.

**Comment by babadoctor** [comment]
Hi Rise,

Thank you for your response,

I did add this to the config.toml file, but for some reason my index.xml only shows a blank page.

![image](https://github.com/AmazingRise/hugo-theme-diary/assets/8715318/d41b8919-d2c1-45ea-8d9e-cdbdfa6c8a1e)

What do you think could be causing this? I have 3 entries in my website which are not drafts.
