### ISSUE TITLE
Google Analytics 4 will be replaced by Universal Analytics

### ISSUE THREAD

**Issue by relaxcn** [AmazingRise/hugo-theme-diary#154]
谷歌分析即将取代老版本的

**Comment by AmazingRise** [comment]
Thanks for your feedback.
Will be fixed later.

**Comment by shinyzhu** [comment]
I don't think you need to do anything.

Google Analytics is a [builtin template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/google_analytics.html) of Hugo. It will add tracking code depends on what your config is. If you are using GA4 and you could get `G-0000XXXXAB`. The template will generate correct gtag script for tracking.

**Comment by relaxcn** [comment]
Yes. Maybe you are right. my Google Analytics is working now.
