### ISSUE TITLE
Way to remove the darkmode toggle?

### ISSUE THREAD

**Issue by koolaidxk1d** [AmazingRise/hugo-theme-diary#156]
I enjoy the automatic dark/light selection based on browser preference, and I would prefer to use only that. The reason is because the utterances comments do not change along with the toggle, so if the visitor is allowed to use the toggle, the browser saves their preference of site background, but the utterances comments remain as their browser-defined preferred theme.

Hopefully that is not too confusing. I'm just hoping there is an **easy way for me to remove the toggle button** from my instance of the theme to prevent it from showing in my deployed site.

example below:

![image](https://github.com/AmazingRise/hugo-theme-diary/assets/81527376/48be081e-0b4b-4e8f-bc05-b6d1b396895d)

**Comment by AmazingRise** [comment]
Hi @koolaidxk1d 
Thanks for your feedback.
But there is a switch to toggle the dark mode feature. Please try this:
https://github.com/AmazingRise/hugo-theme-diary/wiki/Dark-Mode
