### ISSUE TITLE
Add in-site search

### ISSUE THREAD

**Issue by mxcmc** [AmazingRise/hugo-theme-diary#16]
能否添加搜索功能，搜索文章？

**Comment by AmazingRise** [comment]
感谢你的支持。
刚才本人查了一番资料，又仔细考虑了一下。
对于动态网站，搜索功能很好做。但 Hugo 是一个静态网站生成器，这意味着搜索功能需要通过用 Hugo 生成 JSON + Javascript 搜索的方式实现。可惜很难做到全文搜索，对中文进行分词，还有同义词转换。用户体验大打折扣。可以参考[这个链接](https://gohugo.io/tools/search/)。

目前本人的想法是引入正经的搜索引擎，例如 Google。利用 Google 的站内搜索，我们只要在某个合适的地方加搜索框就可以了。

不过由于本人近来有些忙碌，这个功能可能不会很快做出来，所以先加到 Todo List 里面啦。
同时也欢迎 Pull Request。

**Comment by AmazingRise** [comment]
Added Google Custom Search Engine in the latest commit.
[See this for details.](https://github.com/AmazingRise/hugo-theme-diary/wiki/Customization#add-google-search-box-on-your-site)
