### ISSUE TITLE
移动端，文末的脚注跳转回文中的序号时，内容会被导航栏遮挡

### ISSUE THREAD

**Issue by Namarimizu** [AmazingRise/hugo-theme-diary#171]
**Describe the bug**
如题：从文末脚注跳转回文中序号，实际上是把序号所在的那一行置于整个屏幕的顶端，然后就被导航栏挡住了……

**Comment by AmazingRise** [comment]
Hi @Namarimizu 
Thanks for your feedback. But it's by design. Small links are not friendly for mobile users to touch. If we close drawer immediately upon clicking, users would be disappointed on their false trigger.
