### ISSUE TITLE
作者能麻烦您考虑一下加上视频播放功能吗

### ISSUE THREAD

**Issue by goodboylqs** [AmazingRise/hugo-theme-diary#175]
想在网页中方便的插入视频，之前搜索到了一个帖子https://cloud.tencent.com/developer/article/2226121，在本地试用了一下可以完美运行，作者不能考虑实现各大视频网站的视频插入功能，谢谢

**Comment by AmazingRise** [comment]
Hi @goodboylqs 
感谢你的建议。shortcode本质上是一个语法糖，你可以点击b站上的“分享”-“嵌入式代码”来获得嵌入式b站播放器的HTML源码，并粘贴到自己的博客里。这并不需要shortcode。
