### ISSUE TITLE
problem when deploying on netlify or render

### ISSUE THREAD

**Issue by weberlam** [AmazingRise/hugo-theme-diary#19]
I tried to deploy the website on Netlify and Render, but it seems that it just shows the html files out. I cannot figure out why, can you help fix it out? And I am wondering that you could write a doc about the installation and deployment.

1. When I use `hugo server` to generate the website on my computer, it looks well (through localhost:1313).
2. My hugo version is 0.69.0, and I set the hugo version on Netlify to 0.69.0 too. I also tried previous version of hugo but it still doesn't work in Netlify.
3. My OS is win10 while the Netlify's OS is ubuntu 16.04.

**Comment by AmazingRise** [comment]
Hi, weberlam.
Hugo is a static website generator, and it is only a generator. If you get html files after running `hugo`, it indicates that Hugo just works well.
As for deployment, it isn't a thing for Hugo to do. You have to deploy manually. So you can see [this tutorial](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/) for deployment on Netlify.
Thanks.

**Comment by weberlam** [comment]
Hi Rise. Thanks for you answer. I have found where the problem is. It seems that it's about the https. When I use http, the website works well. However, when I turned to https, the problem occurred. I googled the problem and found an answer, which suggests replacing all "http" with "https". I tried so but it just didn't work. I notice that your website runs well with https. Did you meet this problem before? How do you solve that?

**Comment by weberlam** [comment]
> Hi, weberlam.
> Hugo is a static website generator, and it is only a generator. If you get html files after running `hugo`, it indicates that Hugo just works well.
> As for deployment, it isn't a thing for Hugo to do. You have to deploy manually. So you can see [this tutorial](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/) for deployment on Netlify.
> Thanks.

Hi Rise. Thanks for you answer. I have found where the problem is. It seems that it's about the https. When I use http, the website works well. However, when I turned to https, the problem occurred. I googled the problem and found an answer, which suggests replacing all "http" with "https". I tried so but it just didn't work. I notice that your website runs well with https. Did you meet this problem before? How do you solve that?

**Comment by AmazingRise** [comment]
Closed for inactive issue.
If you have further questions, please feedback here, thanks.
