### ISSUE TITLE
dark-mode css file is blocked by browser

### ISSUE THREAD

**Issue by idontwannarock** [AmazingRise/hugo-theme-diary#194]
### Describe the bug

With Chrome opening the generated site, the dark-mode.css is blocked due to CORS problem causing improper rendering of the site.

### To Reproduce

No specific config. Just build and deploy on Github Page.

### Expected behavior

Generated site should be rendered normally.

### Screenshots

![image](https://github.com/user-attachments/assets/eca2ba6d-ed12-427c-a614-9b060e8ea05d)
![image](https://github.com/user-attachments/assets/de25ff1d-1a5c-4704-ace9-98b199163fd0)

### Environment

Hugo version: 0.139.3
![image](https://github.com/user-attachments/assets/f0576d13-f5d7-4c91-a327-c744ef4a50a1)
Chrome version: 131.0.6778.110 (Official Build) (64-bit)
![image](https://github.com/user-attachments/assets/f6b47af5-158e-4cc0-b8ff-bd266489f8cb)

**Comment by AmazingRise** [comment]
Hi idontwannarock

CORS checking is a client-side behavior, usually caused by wrong configurations of gateway. Please check your gateway settings. Thank you.

**Comment by idontwannarock** [comment]
Thanks for the prompt response. I found the problem to be the baseURL was incorrect in the config.toml file. It is normal now after it was fixed.
