### ISSUE TITLE
Pagination icons do not render in safari

### ISSUE THREAD

**Issue by jeffellin** [AmazingRise/hugo-theme-diary#20]
### **Describe the bug**
When using safari on Mac pagination buttons do not show.  Cannot see all posts since you can't page down.  The buttons are there, you can still click in the space that they should be and it works.

**To Reproduce**
visit site on safari

**Expected behavior**
I expect to see the pagination controls

**Environment**
Your Hugo version, generated from `hugo version`.
Hugo Static Site Generator v0.69.0-4205844B/extended darwin/amd64 BuildDate: 2020-04-10T09:15:13ZAnd your browser's basic information.

**Additional context**

**Comment by AmazingRise** [comment]
Hi, jeffellin.
For some reason, there isn't any macOS devices around. Maybe this issue will be fixed **on May or later.** Anyway, I still need further information for troubleshooting:
1. Is this site displayed normally? [Material Icons](https://material.io/resources/icons/?style=baseline)
2. Can you provide your Safari version?
3. Have a visit of [my site](https://amazingrise.net/). And please have a screenshot of this on your safari.
Thanks for the feedback.

**Comment by jeffellin** [comment]
I spent quite a bit of time looking at this today.  It seems the issue is caused by the overflow=x and overflow-y being set to hidden.  I removed these elements from the css and the material now shows.  I am not a css expert so I don't know what the ramifications of removing these are.

Your site does not show the material either.  I have included photos of that as well as photos of .  [my site](www.ellin.com) in safari.

Safari v. 13.1

<img width="362" alt="Item-0_and_DisplaysExtra_and_Item-0" src="https://user-images.githubusercontent.com/11721615/79828570-f2b7e280-836e-11ea-8612-5ebea68572fa.png">

<img width="822" alt="左手的世界" src="https://user-images.githubusercontent.com/11721615/79828464-b71d1880-836e-11ea-8fe7-4dd7d74f6ba0.png">

**Comment by AmazingRise** [comment]
These lines are ported from [original theme](https://github.com/SumiMakito/hexo-theme-Journal/blob/master/source/scss/journal.scss), I don't know if they are not compatible with Safari, for there's no device to test. Thanks for your efforts.
And do you mean [this line](https://github.com/AmazingRise/hugo-theme-diary/blob/52d74750f39bb327708b7069eb905379970cbfd5/assets/scss/journal.scss#L513)?
Does it work by removing only `overflow-y`, or removing both `overflow-x` and `overflow-y`?

**Comment by jeffellin** [comment]
It was in both side-container and extra-container, I did need to remove them boh.

**Comment by AmazingRise** [comment]
OK, please clone `testing` branch to see if there are further questions.

**Comment by jeffellin** [comment]
yes,  that does seem to work,   I see you made a change to 

```
          line-height: 1.2em !important;
```

was that part of the fix or a separate change?

**Comment by AmazingRise** [comment]
A separate change, after i saw your blog. Because I found that the post-subtitle is not showing very well. :)
Thanks for your feedback, now I will merge to master.
