### ISSUE TITLE
Some contents conflict with Vue template grammer

### ISSUE THREAD

**Issue by ffffansz** [AmazingRise/hugo-theme-diary#22]
Thank for your excellent theme!

**Describe the bug**

One of my posts contains some strings like "You can format the output string by using `docker ps -f {{ .ID }}`", and after starting hugo server, this page will be empty, and the console in developer tools of Chrome will report error. The screenshot is displayed below.

我的一篇文章里包含了一些用"{{"和"}}"包裹的字符，但是当我运行hugo server后，发现该文章的网页打开之后是一片空白，Chrome的开发者工具中也报了错，错误截图在下面贴出。

After debugging, I think this bug is caused by the Vue template grammer since it uses "{{ }}" as the delimiter too, which will conflict with my post's content.

经过调试，我认为这个Bug是由Vue的模板语法引起的，它会将Markdown文件内的"{{ xx }}"当做模板来处理，进而导致了Bug的产生。

I fix this bug in my project by adding an option to `new Vue` statement in `journal.js`:

我在自己的项目中做了如下的修改，修复了这个Bug，在`journal.js`文件中：

```javascript
app = new Vue({
    el: '#app',
    delimiters: ['${{{{{{{{', ']}'],
    data: {
        scrollY: 0,
        navOpacity: 0,
        isDrawerOpen: false,
        mounted: false,
    },
    // ...
```

And everything works well.

然后一切都正常了。

**To Reproduce**

One can modify the exampleSite's content, add some strings like "{{ .XX }}". Then run the hugo server. 

你可以修改exampleSite中的任意一篇文章，添加一些"{{ xx }}"类的内容，从而复现该问题。

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18579977/80067997-6de8e680-8571-11ea-903b-c4f4e89fb3c0.png)

**Environment**

Hugo Static Site Generator v0.64.0/extended windows/amd64 BuildDate: unknown

And I also tried higer version, the bug still exists.

我使用的Hugo版本如上，在调试过程中，我也使用了更高版本的Hugo，但是问题依旧。

**Additional context**

**Comment by AmazingRise** [comment]
其实你可以使用
```html
<div v-pre>
{{ Contents }}
</div>
```
这样可以防止 Vue.js 解析这段文本，并且不需要修改代码的其他部分。我的博客里面一些涉及到 {{ }}的代码也是这么做的。甚至你可以将整篇文章用这个包围。

另外由于 Hugo 在 Vue.js 之前被解析，所以这两者也不会产生冲突。

**Comment by ffffansz** [comment]
学习到了，因为不了解Vue.js，所以也没有用到这个解决办法。可以考虑对主题进行修改，或者在Wiki中进行说明，避免其他用户遇到相同的问题。

**Comment by ffffansz** [comment]
另外还想提一点（就不另开一个issue了），数学支持可以考虑使用KaTex，[这里](https://www.intmath.com/cg5/katex-mathjax-comparison.php)有MathJax和KaTex的速度对比，我打算先部署到自己的站点试一下。

**Comment by AmazingRise** [comment]
> 另外还想提一点（就不另开一个issue了），数学支持可以考虑使用KaTex，[这里](https://www.intmath.com/cg5/katex-mathjax-comparison.php)有MathJax和KaTex的速度对比，我打算先部署到自己的站点试一下。

好的 感谢建议，我会看看KaTeX的速度的。至于Wiki的话，我有空添加一下。
非常感谢你的反馈！

**Comment by AmazingRise** [comment]
感谢建议.
在去掉 Vue 之后,KaTeX 已经加入到主题中.
代码已经发布到 testing 分支,测试结束后会放到主分支中.
