### ISSUE TITLE
Add reading time to each article

### ISSUE THREAD

**Issue by jenlky** [AmazingRise/hugo-theme-diary#23]
This is an enhancement idea. The diary can include an estimation of the amount of time required to finish an article. That would make it better.

**Comment by AmazingRise** [comment]
Done.
Please clone the testing branch, and add it to your site's `config.toml`:
```toml
[params]
enableReadingTime = true
```
Then see if the reading time is accurate.

**Comment by AmazingRise** [comment]
(Closed accidentally just now)

**Comment by AmazingRise** [comment]
Merged into master.
https://github.com/AmazingRise/hugo-theme-diary/commit/68e14e3ac9cc9f1100241b7f6bdf408e07759f85
