### ISSUE TITLE
主题评论设置

### ISSUE THREAD

**Issue by ChenChilde** [AmazingRise/hugo-theme-diary#26]
我想用Valine来做评论，但是主题默认的是Gitalk 怎么按照https://github.com/AmazingRise/hugo-theme-diary/wiki/Comment-Area  进行修改配置了。主题文章就没评论了。
https://blog.chenmingmao.com
![xx](http://www.xxrrtt.com/xx.png)

**Comment by AmazingRise** [comment]
你的comment.html是不是改动过？
`$(new Valine({`的前面多了一个`$(`

**Comment by ChenChilde** [comment]
的确！修复了！好的感谢了~

**Comment by AmazingRise** [comment]
好的 没事
