### ISSUE TITLE
增加站點圖像

### ISSUE THREAD

**Issue by zisen123** [AmazingRise/hugo-theme-diary#29]
希望能將站點圖像功能加入todo

**Comment by AmazingRise** [comment]
hi, zisen123
你可以再详细描述一些吗？站点图像指的是什么

**Comment by zisen123** [comment]
如圖所示, 左邊是我的wordpress博客, 可以設置站點圖像, 而右邊的hugo顯示的則是一個地球的標志.
![](https://pic.downk.cc/item/5ea8d73cc2a9a83be5bbecae.jpg)
下圖是wordpress後臺設置站點圖像的地方
![](https://pic.downk.cc/item/5ea8d73cc2a9a83be5bbecde.jpg)

**Comment by AmazingRise** [comment]
在`config.toml`里面加一个
```toml
[params]
favicon=xxxxx
```
就可以了

我忘记写到维基里面了233

**Comment by zisen123** [comment]
謝謝, 現在可以使用了.
