### ISSUE TITLE
markdown table is not rendered.

### ISSUE THREAD

**Issue by yech1990** [AmazingRise/hugo-theme-diary#3]
```
| id  | name |
| --- | ---- |
| 1   |  xxx |
| 2   |  xxx |

```

**Comment by AmazingRise** [comment]
I've checked the original version of this theme in Hexo.js.
In fact the table shown in Hexo.js is the same as now it is.
The table is indeed rendered, without border.
It maybe a feature or a bug, left in the original version.
Whatever it is, I'll fix it, as the table with no border really seems weird.
Thanks for that.

**Comment by yech1990** [comment]
Thank you @AmazingRise. This looks really messy, especially for large tables with too much columns.
It would be nice if the bootstrap table framework can be adopted for paging and filtering.

I did try to make a fork for this feature, but it is too difficult for me. Looking forward to the update.

**Comment by AmazingRise** [comment]
Fixed. And I made the table responsive to content width.
BTW I also fix some small issues at the same time.
Now please pull the latest version to have a view of it.

As for technical detail, I added four bootstrap classes to all the table elements. [Click here to view related files.](https://github.com/AmazingRise/hugo-theme-diary/blob/master/static/js/table.js)

That's a dirty hack, in some sense. Under the limitation of Hugo's markdown renderer, I did my best 😂️.
If some other questions appear, please feedback here. Thanks.

**Comment by yech1990** [comment]
Much better! This commit solve my problem.
