### ISSUE TITLE
Adding a FAQ page with questions and answer in Drop down menu

### ISSUE THREAD

**Issue by motilalmeher** [AmazingRise/hugo-theme-diary#30]
I want to add a new page (not a post) for Faqs where I will put questions and answer like the drop-down style. For this what should I do? I mean I have added a FAQ in menu bar. So when I will click on faq I want to redirect to faq page(where I only want drop-down faqs and no menu in left side).

Summary of problem:
1) how to create a web page(not a blog post) where I need drop-down style using markdown.
2) where to create i mean in which directory and how to add URL.
3)how to hide side menu while getting into one web page.

huog version v0.69.1-17661DEB windows/64 bit

**Comment by AmazingRise** [comment]
Hi, motilameher.
First, I have to declare that I'm only a theme porter, and a theme is used to define the style of your contents. How to render your markdown -- it is the job of makrup engine. So as for your questions, I can only give you some suggesstions.

For question 1&2 : 
To create a drop-down menu, you can try to create a HTML page, and you may have to write several lines of javascript code. Though it's not recommended to use your own javascript code under hugo, which may cause some ploblems, there are many ways to achieve, [for example](https://discourse.gohugo.io/t/add-raw-html-page-as-post/15434/5).

For question 3:
Showing side menu is a design of this theme. If you don't want this design, I hope you can read Hugo documentations by yourself and DIY the page located at `/layout/paritals/sidebar.html`.

Thank you for understanding.
