### ISSUE TITLE
featured_image does not work with page resources

### ISSUE THREAD

**Issue by jordan-dlh** [AmazingRise/hugo-theme-diary#34]
When featured_image refers to a page resource, the template does not account for it and the link it creates is wrong.

To reproduce it, add an image as a page resource and refer to it as a featured_image in the page's parameters. It should link to this image in the page and in the list, but it doesn't because the link that is generated is an absolute link that does not account for the page url.

I made a pull request #33 that fixes that while also keeping the previous behavior when it is not a page resource.

**Comment by AmazingRise** [comment]
Thanks for your efforts.
