### ISSUE TITLE
valine留言了为什么看不见呢？

### ISSUE THREAD

**Issue by Newamber** [AmazingRise/hugo-theme-diary#35]
我开始以为是我自己的leancloud相关的Key没有设置对，但是我在大佬您的左手的世界网站下面文章留言后也看不见评论呢？

**Comment by AmazingRise** [comment]
hi，我这里有的啊。
你报一下你现在的Valine的版本是多少。
如果能附上截图就更好了

**Comment by AmazingRise** [comment]
如果你的版本里面没有journal.html这个文件，并且你的 Valine 是最新版本（1.4.14）的话
说明是这个问题：
https://github.com/AmazingRise/hugo-theme-diary/issues/21
解决办法有两种
1. 拉取最新的master分支，用 Valine 1.4.5，很稳定不会有问题。
2. 拉取最新的testing分支，用 Valine 1.4.14，正在测试中，目前我博客上的版本就是这个。如果在你那边看的也有这个问题的话，说明testing分支仍然存在问题，这种情况请在这里反馈给我。

**Comment by Newamber** [comment]
我现在使用的就是1.4.5，我不知道是否还需要额外配置什么，我自己的博客评论后看不见留言，也看不见在您博客文章的留言

**Comment by AmazingRise** [comment]
我这边用Chrome和Firefox都无法复现。试了一下手机4G+Chrome也没有复现出问题。不能复现的话就有点麻烦了。
方便贴一下你的Hugo博客的网址吗？我在这边看一下是不是也有问题

**Comment by Newamber** [comment]
https://newamber.netlify.app/

**Comment by Newamber** [comment]
不好意思，看来是公司网络问题，我能访问我的网站，但是看不到留言区，我试着用手机和自己的4G流量留言，发现是可以看到的，但是从公司访问自己的博客，就看不到留言区，我猜应该是公司的网络拦截了leancloud的数据

**Comment by Newamber** [comment]
不纠结这个问题了，感谢您的及时回复，主题不错，我会继续使用和研究滴~
