### ISSUE TITLE
Dark mode 没有在文章的 list 中生效

### ISSUE THREAD

**Issue by DarkKate** [AmazingRise/hugo-theme-diary#37]
**Dark mode 没有在文章的 list 中生效**
即使开启dark mode，文章中的列表的文字还是按light mode显示的（即文字还是黑色）

**案例链接**
[作者的博客中的一篇文章](https://amazingrise.net/posts/getting-to-know-vue-components/)

**Comment by AmazingRise** [comment]
好吧。。我昨晚发现了，打算今早再改
现在正常了
anyway 感谢反馈 😂️
