### ISSUE TITLE
Tags and Categories pages

### ISSUE THREAD

**Issue by thebestwj** [AmazingRise/hugo-theme-diary#39]
Hi,Rise
不知道你有没有计划美化一下标签页和分类页
现在这样显示一行文字，
如果标签分类很多的话感觉不是特别好看，而且很难找到想要的

**Comment by AmazingRise** [comment]
Hi
这个之前有人提过，但是我现在暂时没有想到什么好的方案。

不过至少要等几个月之后才有时间精雕细琢，唉。

**Comment by AmazingRise** [comment]
@thebestwj 
我在想，如果我直接去掉这个地方的翻页，是不是会好很多？

**Comment by thebestwj** [comment]
@AmazingRise 
我觉得可能分个栏就会好看点，像这样
https://themes.gohugo.io//theme/Binario/tags
或者做成就做成标签式的，像这样
https://themes.gohugo.io//theme/hugo-vitae/tags

**Comment by AmazingRise** [comment]
Upstream issue, needs to be fixed.
Pagination will always generate, despite the `.Paginator` is deleted.
https://discourse.gohugo.io/t/cannot-disable-pagination-in-terms-page-even-after-removing-paginator/25862/3

**Comment by zane-ng** [comment]
Hello,

不知道是否知道 [bigfoot.js](http://www.bigfootjs.com/)？这个 JavaScript 能将 Markdown 的脚注自动变成按钮，然后在按下的 pop-up 中显示脚注内容。这个 JS 有个优化版本叫 [littlefoot](https://github.com/goblindegook/littlefoot). bigfoot/littlefoot 产生的脚注样式可以滚动显示内容，同时也可以继续显示链接以及其他样式文本。

我在想，是否可以参考 bigfoot.js 将每一个 tag 变成一个按钮，然后在按钮 pop-up 中按照年月顺序显示指向文章的链接？bigfoot/littlefoot 本身都提供了强大的自定义功能，所以似乎可以直接使用 littlefoot.js 来做个针对 tag 和分类的版本。

**Comment by AmazingRise** [comment]
> Hello,
> 
> 不知道你是否知道 [bigfoot.js](http://www.bigfootjs.com/)？这个 JavaScript 能将 Markdown 的脚注自动变成按钮，然后在按下的 pop-up 中显示脚注内容。这个 JS 有个优化版本叫 [littlefoot](https://github.com/goblindegook/littlefoot). bigfoot/littlefoot 产生的脚注样式可以滚动显示内容，同时也可以继续显示链接以及其他样式文本。
> 
> 我在想，是否可以参考 bigfoot.js 将每一个 tag 变成一个按钮，然后在按钮 pop-up 中按照年月顺序显示指向文章的链接？bigfoot/littlefoot 本身都提供了强大的自定义功能，所以似乎可以直接使用 littlefoot.js 来做个针对 tag 和分类并符合本主题样式的版本。

我觉得可，现在的 tag 功能的确不好用，所以我一直没用（x
这倒是个好办法，等我有空看一下这个能不能在Hugo里实现。

感谢建议！

**Comment by xiaohao890809** [comment]
是的，云标签会比较美观些

**Comment by yoziming** [comment]
Hi，這個主題真的非常簡潔美觀，我第一眼看到整個驚豔。
唯獨就是標籤與歸檔頁面(希望可以增加到年-季-甚至月份)，且當資料筆數太多時，間隔太大會不好看，希望有**緊湊的排版樣式**可選。
前端這塊實在弄不懂，拜託了!
