### ISSUE TITLE
Automatic enabling of dark mode

### ISSUE THREAD

**Issue by james-cccc** [AmazingRise/hugo-theme-diary#40]
**Describe the bug**
The instructions on the Wiki for automatically enabling dark mode don't seem to work [wiki link](https://github.com/AmazingRise/hugo-theme-diary/wiki/Dark-Mode)

**To Reproduce**
Always reproducible 

**Expected behavior**
The file `journey.js` to exist.
I've found the same section in `journal.html` however amending this doesn't seem to have any effect. 
```
        // From https://www.jdeal.cn/archives/Dark.html
        var night = document.cookie.replace(/(?:(?:^|.*;\s*)night\s*\=\s*([^;]*).*$)|^.*$/, "$1");
        if (night==""){
            if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
                this.toggleDarkMode();
            }
        }else{
            // If night is not empty
            if (night=="1") {
                this.toggleDarkMode();
            }
        }
```

**Environment**
Hugo Static Site Generator v0.67.1 linux/amd64 BuildDate: 2020-03-16T08:10:43Z

**Additional context**
It would be great to have this as a parameter in the toml configuration. Let me know if you need anything else.

**Comment by AmazingRise** [comment]
Hi, thanks for your feedback.
But it works well for me here.
To validate that, I've added several `console.log`, like this:
```javascript
// From https://www.jdeal.cn/archives/Dark.html
        var night = document.cookie.replace(/(?:(?:^|.*;\s*)night\s*\=\s*([^;]*).*$)|^.*$/, "$1");
        if (night==""){
            console.log("No cookies detected.");
            if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
                console.log("Dark mode enabled by default.");
                this.toggleDarkMode();
            }
        }else{
            // If night is not empty
            if (night=="1") {
                this.toggleDarkMode();
            }
        }
```
When I switched my browser to dark mode, it changed as excepted, both in Firefox and Chromium.
![图片](https://user-images.githubusercontent.com/8315221/82467737-93c3c580-9af4-11ea-943d-d1f247267513.png)

As for wiki, thanks for your advice, I will update soon.
And I will also consider making it a variable.

**Comment by james-cccc** [comment]
Thanks Rise, just given your new update a go and working perfectly

**Comment by AmazingRise** [comment]
OK. If you have any further questions, please feedback. Thanks.
