### ISSUE TITLE
Changing color scheme

### ISSUE THREAD

**Issue by james-cccc** [AmazingRise/hugo-theme-diary#41]
**Describe the bug**
Modifying `$color-accent:` per the documentation on the [wiki](https://github.com/AmazingRise/hugo-theme-diary/wiki/Customization) seems to have no effect. I've done full rebuilds and no had no luck. 

**To Reproduce**
Always reproducible. 

**Expected behavior**
Colour scheme to change

**Environment**
Hugo Static Site Generator v0.67.1 linux/amd64 BuildDate: 2020-03-16T08:10:43Z

**Additional context**
Excellent theme by the way

**Comment by AmazingRise** [comment]
Hi, thanks for your feedback.
You are using normal version of Hugo, not extended.
It means any `scss` files will not be compiled, even after you've changed it.
Please consider switching your Hugo version to extended. Here is the output of `hugo version` of extended version:
```
Hugo Static Site Generator v0.69.2/extended linux/amd64 BuildDate: unknown
```

And I will add a note on wiki about this. Thanks.

**Comment by james-cccc** [comment]
Thanks, just tried that and now working as expected. Appreciate the help
