### ISSUE TITLE
Unable to set up disqus

### ISSUE THREAD

**Issue by jenlky** [AmazingRise/hugo-theme-diary#42]
**Describe the bug**
Unable to set up disqus for my posts.

**To Reproduce**
I have added disqusShortname = "jenlky" to the config.toml. Neither did I set the frontmatter comment = false. 

It exists in comment.html too:

```
{{ if .Site.Params.disqusShortname }}
<div class="post-comment-wrapper">
  {{ template "_internal/disqus.html" . }}
</div>
{{ end }}
```
**Expected behavior**
By right, disqus should appear below all the posts.

**Screenshots**

**Environment**
Your Hugo version, generated from hugo version.

I downgraded my hugo version from v0.69.0 to v0.68.3:

Hugo Static Site Generator v0.68.3-157669A0 windows/amd64 BuildDate: 2020-03-24T12:04:36Z
Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Additional context**

**Comment by AmazingRise** [comment]
Please try this commit, and see if Disqus works.

https://github.com/AmazingRise/hugo-theme-diary/commit/b4c734f9d845231025817c5fe661b940dae81ec2

Now it works for me. If yours also works fine, even when online, please close this issue.
Thanks for your support.

**Comment by jenlky** [comment]
I've git pull the theme and ensured nothing is overriding the theme changes. However, it still doesn't work for me and I'm not sure what's the problem. 

Let me know if you need any code/screenshots to show it!

**Comment by AmazingRise** [comment]
Now please visit https://amazingrise.net/posts/building-openjdk/
You may see a Disqus comment at the bottom, like this:
![image](https://user-images.githubusercontent.com/8315221/82785224-ba875080-9e94-11ea-9f48-352b832f07ba.png)

Here is my `config.toml`:
```toml
[params]
subtitle = "Rise's Blog"
enableGitalk = false
enableReadingTime = true
# enablevaline = true
disqusShortname = "jenlky"
```

**Comment by jenlky** [comment]
I found out what's the problem - I didn't put my disqusShortname config under params in config.toml 🤦‍♂️  

Thanks for sharing your screenshots and config settings! 谢谢🙏

**Comment by AmazingRise** [comment]
haha, anyway, thanks for your feedback!
感谢反馈！
