### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by jintolonappan** [AmazingRise/hugo-theme-diary#44]
Hi,
Beautiful theme. Thanks for creating it.
I have a feature request. Can you please add a 'About' section with a static landing page?
Examples: https://themes.gohugo.io//theme/hyde-hyde/about/
https://themes.gohugo.io/theme/hugo-coder/about/

**Comment by AmazingRise** [comment]
Hi, jintolonappan.
You can create an `about.md` under `/contents/`. Then you can access this page with `your-site.com/about`
Finally, add `/about` to the sidebar, as I've said in [wiki](https://github.com/AmazingRise/hugo-theme-diary/wiki/Customization#customize-sidebar).
Now you are able to see `About` on the sidebar, and by clicking it you can access your About Page.
