### ISSUE TITLE
Vue reference error

### ISSUE THREAD

**Issue by nicholaskajoh** [AmazingRise/hugo-theme-diary#46]
**Describe the bug**
Vue throws a reference error when the template syntax `{{ }}` is used in a post, and the page doesn't render properly (i.e blank page).

**To Reproduce**
Create a post and add `{{ helloWorld }}`.

**Expected behavior**
`{{ helloWorld }}` should be treated like any other text and the page should be rendered properly.

**Screenshots**
![Screenshot from 2020-06-02 20-10-41](https://user-images.githubusercontent.com/17048405/83560036-75ef5b00-a50d-11ea-9a51-e30143d3406e.png)

**Environment**
Hugo Static Site Generator v0.71.1/extended linux/amd64 BuildDate: 2020-05-25T13:06:06Z
Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by nicholaskajoh** [comment]
I've patched my fork by adding `v-pre` in single.html. Hope this will not have any side effects.

**Comment by AmazingRise** [comment]
Hi, nichola
I'll try to solve this problem.
For temporary fix, you can use `<v-pre>` outside of the code block.

About side effects:
There shouldn't any side effects, as far as I know, if `v-pre` is put on the proper position.
And if possible, I will find some other elegant way to solve this issue.

Thanks for your and @wych42 's feedback.

**Comment by AmazingRise** [comment]
Fixed in https://github.com/AmazingRise/hugo-theme-diary/commit/dbe3f9a9ebf7900f7c745eb6262b95c5c307fcc6

And if there are any further ploblems, please feedback here.
Or you can close this issue.
