### ISSUE TITLE
[Feature request] more optional meta tags

### ISSUE THREAD

**Issue by vanhumbeecka** [AmazingRise/hugo-theme-diary#48]
It would be nice to have some more meta-tags available for better discoverability with other websites.

For example:
- optional manifest.json file
- optional `og:***` tags (see https://ogp.me/)
- optional `twitter:***` meta tags (see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started)
- ...

**Comment by AmazingRise** [comment]
Thanks for your feedback, and I'll add it someday.
(Recently I'm busy on something else, so you may not see this feature soon.)

Welcome pull requests. And when I start to do this, I'll put it into [Projects](https://github.com/AmazingRise/hugo-theme-diary/projects).

**Comment by vanhumbeecka** [comment]
I've created a PR to add these (optional) changes inside this template.
All configurable with the `.toml` file.

**Comment by AmazingRise** [comment]
Thanks for your contribution in #52 !
