### ISSUE TITLE
How to use the home page as an about page

### ISSUE THREAD

**Issue by nicholaskajoh** [AmazingRise/hugo-theme-diary#49]
How do I use the home page as an about page and not a list of posts? (I'm using `/blog` for posts)

**Comment by AmazingRise** [comment]
Hi nichola,
It seems that you've done this.
When I visit your homepage, it is an about page.

Besides, I suggest reserving the copyright declaration of this theme, for respecting MIT license and my efforts on this project.
Thanks for your support, and feedback these days.

**Comment by Victorfy** [comment]
@AmazingRise 请问是如何改的

**Comment by AmazingRise** [comment]
You can put index.md under content folder. Then it will replace the default index page.
This use case is described in Hugo Documents in fact, and not related to a specific theme. (That is to say, this is applied to every themes)

As far as I remembered, the related section is called lookup order in Hugo Documents.


你可以把index.md放到content文件夹下。之后这个index.md就会替换掉默认的首页了。这个用法在Hugo的文档里描述过，并且与某个特定的主题无关。也就是说，你在任何主题上都可以这么用。

我记得和这玩意有关的内容在“lookup order”一节

**Comment by nicholaskajoh** [comment]
It's actually `_index.md` i.e [with an underscore](https://gohugo.io/templates/homepage/#add-content-and-front-matter-to-the-homepage). This is what I tried first but it didn't work.
