### ISSUE TITLE
Shouldn't last modified be at top of the page?

### ISSUE THREAD

**Issue by nicholaskajoh** [AmazingRise/hugo-theme-diary#50]
I'm looking at it from a UX perspective. Last modified is more relevant to me before reading an article rather than after. I think it should be at the top of the page with the other post metadata. What do you think?

**Comment by AmazingRise** [comment]
Hi, thanks for your feedback.
And I have considered this carefully for some while.

1. If modify time is added at the top of the page, along with create time, it seems okay on PC. However, on mobile view, it is too crowded and complicated. It breaks the design principle of the original theme -- elegant and friendly to mobiles.
2. I've also referred to some other themes, a lot of them put the modify time at the bottom page. I'm not a professional desinger, but I think it may be resonable when a lot of the theme creators do so.
3. Sometimes last modify time doesn't work for me here. It is not as accurate as I thought it should be. In most situations, I have to write `lastmod` in front matter manually. So I think it should not be placed at such a obvious position.

So I may not fix this issue.

Anyway, thanks for your feedback.

**Comment by nicholaskajoh** [comment]
Got it! Thanks for the elaborate reply.
