### ISSUE TITLE
Disqus comments section not displayed

### ISSUE THREAD

**Issue by nicholaskajoh** [AmazingRise/hugo-theme-diary#51]
**Describe the bug**
The Disqus comment section is not being displayed when `disqusShortname` is set.

**To Reproduce**
Add `disqusShortname` to the root of your config.toml as per [the docs](https://github.com/AmazingRise/hugo-theme-diary/wiki/Comment-Area#disqus) and then create a new post.

**Expected behavior**
The Disqus comments section should appear.

**Environment**
Hugo Static Site Generator v0.71.1/extended linux/amd64 BuildDate: 2020-05-25T13:06:06Z
Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Additional context**
I've put `disqusShortname` under `[params]` as a workaround.
```toml
[params]
    disqusShortname = "xxxxx"
```

**Comment by nicholaskajoh** [comment]
PS: I replaced `.Site.Params.disqusShortname` with `.Site.DisqusShortname` in partials/comment.html but that didn't work. :thinking:

**Comment by AmazingRise** [comment]
Thanks for your feedback.
But it works for me here.
![图片](https://user-images.githubusercontent.com/8315221/83774904-e71f4180-a6b8-11ea-9a79-1072c6dad97a.png)

**Comment by nicholaskajoh** [comment]
That's due to this workaround (https://github.com/nicholaskajoh/alphacoder.xyz/commit/5a35ada86bd0cfde807240ffb3cc88cd9a71dcb4). I mentioned this so that a fix would go out to help other users of this theme.

**Comment by AmazingRise** [comment]
Oh, sorry I didn't find the link before.
Got it now and I modified [Wiki Page](https://github.com/AmazingRise/hugo-theme-diary/wiki/Comment-Area#disqus).

Thank you very much.
