### ISSUE TITLE
ToC Auto Collapsing doesn't work on some ToC structure

### ISSUE THREAD

**Issue by swhhy** [AmazingRise/hugo-theme-diary#54]
**Describe the bug**
Hi, thanks for your theme😀! and for the issue : my blog is writted in the format of Markdown, but the ToC is empty. Just shows "-CATALOG-", and nothing else. 

**Environment**
Hugo Static Site Generator v0.73.0/extended windows/amd64
browser: chorme latest version

**Comment by AmazingRise** [comment]
Hi, swhhy.
Do you have a demo page to show me that?
Or how to reproduce this issue?

**Comment by swhhy** [comment]
https://swhhy.github.io/ 
请您看看，就那个markdown的ToC有一两行, 其他的都是空的。

**Comment by swhhy** [comment]
@AmazingRise 
https://swhhy.github.io/
请您看看，就那个markdown的ToC有一两行, 其他的都是空的。

**Comment by AmazingRise** [comment]
能否贴上这个Markdown的全部源码？我这边测试了一下三级标题，还是没法复现
谢谢

**Comment by swhhy** [comment]
---
title: "MarkDown语法笔记"
date: 2019-03-18T02:01:58+05:30
draft: false
description: "markdown语法笔记"
tags: [MarkDown,]
featured_image: "/images/1.jpg"
categories: 杂
comment : false
---

### markdown语法

***

* **使用#号标记标题**

  ```
  # 一级标题
  ## 二级标题
  ### 三级标题
  以此类推 最高六级
  ```

#    一级标题
##     二级标题
###      三级标题
​       以此类推 最高六级



* **字体**   

  ```
  *斜体文本*
  **粗体文本**
  ***粗斜体文本***
  ```

  *斜体文本*
  **粗体文本**
  ***粗斜体文本***

  

* **分割线**

  ```
  ***
  ```

  ***

  

* **删除线**

  ```
  ~~这里被删掉了~~
  ~~this is deleted~~
  ```

  ~~这里被删掉了~~

  ~~this is deleted~~

  

* **下划线**

  ```
  <u>带下划线文本</u>
  ```

  <u>带下划线文本</u>

  

* **脚注**

  ```
  [^要标注的文本]
  
  eg：
  创建脚注格式类似这样[^GGBIRD]
  [^GGBIRD]:卖鱼人王雷的梗，暗指小小鸟
  ```

  创建脚注格式类似这样 [^GGBIRD]  

  [^GGBIRD]: 卖鱼人王雷的梗，暗指小小鸟  

  

* **无序列表**

  ```
  * first
  * second
  * third (*后面一个空格)
  ```

* first
* second
* third



* **有序列表**

  ````
  1. first
  2. second
  3. third （.后面一个空格）
  ````

  1. first

  2. second

  3. third

     

* **列表嵌套**

  ```
  只许在子列表前加一个tab or 4*space
  1. first
  	* 11
  	* 22
  2. second
  	* 一
  	* 二
  ```

1. first
  * 11
  * 22
     * 33
        * 44
          	* 55
2. second
  * 一

  * 二

    

* **区块**

  ````
  > 区块引用
  > bird
  > dog
  ````

  >区块引用
  >bird
  >dog   

  ```
  > oasuihf
  > > asedg
  > > > sege
  ```

  >oasuihf
  >>asedg
  >>
  >>>sege

  ```
  > 区块中使用列表
  > 1. first
  > 2. second
  ```

  > 区块中使用列表
  > 1. first
  > 2. second

  ```
  * first
  	> 列表中使用区块
  	> 同上 tab or 4*space
  * second
  ```

  * first
    > 列表中使用区块
    > aegwagn

  * second

  

* **代码**

   ```
    c语言中的输出函数是`printf()`
    python中的输出函数是`print()`
   ```
    import time
    time.sleep(1)
    ```
   
    ```
 ```
  
  c语言中的输出函数是  `printf() `  
  

python中的输出函数是`print()`

 ```
  import time
  time.sleep(1)
  ```



* **链接**

  ```
  了解详情请访问[pornhub](www.pornhub.com)
  or
  <www.pornhub.com>
  ```

  了解详情请访问[pornhub](www.pornhub.com)
  or
  <www.pornhub.com>

  ```
  这个链接用1作为网址变量[pornhub][1]
  这个链接用2作为网址变量[xvideos][2]
  然后在文档的结尾为变量赋值(网址)

[1]:http://www.pornhub.com/
[2]:http://www.xvideos.com/
  ```

  这个链接用1作为网址变量[pornhub][1]
  这个链接用2作为网址变量[xvideos][2]
  然后在文档的结尾为变量赋值(网址)

  [1]:http://www.pornhub.com/
  [2]:http://www.xvideos.com/
  []:

* **图片**

  ```
  第一种：
  ![](C:\Users\dell\Pictures\666\sunn.bmp "sun")

  第二种：（使用img标签还可以指定图片大小）
  <img src="C:\Users\dell\Desktop\sun.jpg" width="20%">
  ```

![](C:\Users\dell\Desktop\sun.jpg "sun")

<img src="C:\Users\dell\Desktop\sun.jpg" width="20%">



* **表格**

  ```
  制作表格使用 | 来分隔不同的单元格，使用 - 来分隔表头和其他行。
|  表头   | 表头  |
|  ----  | ----  |
| 单元格  | 单元格 |
| 单元格  | 单元格 |

     -: 设置内容和标题栏居右对齐。
     :- 设置内容和标题栏居左对齐。
     :-: 设置内容和标题栏居中对齐。

| 左对齐 | 右对齐 | 居中对齐 |
| :-----| ----: | :----: |
| 单元格 | 单元格 | 单元格 |
| 单元格 | 单元格 | 单元格 |
  ```

  | 表头   | 表头   |
  | ------ | ------ |
  | 单元格 | 单元格 |
  | 单元格 | 单元格 |

| 左对齐 | 右对齐 | 居中对齐 |
| :----- | -----: | :------: |
| 单元格 | 单元格 |  单元格  |
| 单元格 | 单元格 |  单元格  |


  ```

**Comment by swhhy** [comment]
这样吗？😥

**Comment by swhhy** [comment]
[markdown语法.txt](https://github.com/AmazingRise/hugo-theme-diary/files/4897169/markdown.txt)

**Comment by AmazingRise** [comment]
好的，我有空调查一下问题原因。最近比较忙，可能要过几天，新的进展我会在此告知。

你可以通过下面链接中所说的办法禁用auto collapse功能，以保证博客目录正常显示，不会被折叠：
https://github.com/AmazingRise/hugo-theme-diary/wiki/Table-Of-Contents#disable-toc-auto-collapse

**Comment by swhhy** [comment]
谢谢您百忙之中抽空回复，因为这并不影响主题的整体使用，所以您大可有空再帮助我。BTW，我试过使用 `disableAutoCollapse = true` ，但仍然出现了之前的问题。

**Comment by AmazingRise** [comment]
> 谢谢您百忙之中抽空回复，因为这并不影响主题的整体使用，所以您大可有空再帮助我。BTW，我试过使用 `disableAutoCollapse = true` ，但仍然出现了之前的问题。

感谢反馈，最新的commit修复了没法disableAutoCollapse的问题。
但关于此issue的问题仍在调查。

https://github.com/AmazingRise/hugo-theme-diary/commit/248b6008b45ee9af2dcbdc6e8af9285c3eb9f2e8

**Comment by swhhy** [comment]
在最新的版本中，我发现ToC只可以显示markdown文本的第一行，和标题<h1>-<h6>（无论标题在文本的什么位置）。希望这可以帮到你。

**Comment by swhhy** [comment]
在最新的版本中，我发现ToC只能显示markdown文本的第一行和标题`<h1>`-`<h6>`(无论标题在文本的什么位置)，希望这能帮到你。

**Comment by AmazingRise** [comment]
> 在最新的版本中，我发现ToC只能显示markdown文本的第一行和标题`<h1>`-`<h6>`(无论标题在文本的什么位置)，希望这能帮到你。

是的 因为我上次推的是`Fix disableAutoCollapse`。

这个问题已经修复，是`对折叠全部目录的判断`有问题。
本地测试通过了，劳烦你那边测试一下，谢谢。

（我提交commit的时候写了#54，然后GitHub自动关了...太尴尬了）

This issue has been fixed. The bug is caused by `misjudgement of collapsing all classes`.

**Comment by swhhy** [comment]
hh，感谢！
