### ISSUE TITLE
shortcode for images

### ISSUE THREAD

**Issue by STYJ** [AmazingRise/hugo-theme-diary#55]
Hi Rise, is it possible to create a custom hugo shortcode for images so that you can do the following:

1. resize
2. align
3. add caption 

Maybe something like https://themes.gohugo.io//theme/cupper-hugo-theme/cupper-shortcodes/#figurecupper

**Comment by AmazingRise** [comment]
Good idea, I'll try to implement.
Thanks for your feedback.

**Comment by STYJ** [comment]
Thank you, let me know if you need any help and I will try my best to help you! :)

**Comment by AmazingRise** [comment]
Hi, STYJ.
I added a `insertFigure` command, see [wiki](https://github.com/AmazingRise/hugo-theme-diary/wiki/Inserting-Figures) for details.
And I push the code to master branch.

Please try it.
If no further problems are found, please close this issue.

Thanks for your support.

**Comment by STYJ** [comment]
Hi Rise, thank you for the quick work! I have tested it and it is really good! 

However, I had 1 problem - when I tried to use a .gif file for img `insertFigure`, the gif shows up but it doesn't play. Is it possible to also play gifs?

**Comment by AmazingRise** [comment]
And I have to say, this is only a wrapper of Hugo's image processor.
If you want to insert gif files, in the way other figures did, you can ditrctly write HTML code in your content.
(And don't forget to switch on safe HTML option in config.toml)

As for how to write, you can refer to `/themes/diary/layout/shortcodes/insertFigure.html`.

**Comment by AmazingRise** [comment]
And I have to say, this is only a wrapper of Hugo's image processor.
The reason for that may be Hugo's image processor convert the gif into a static image when cropping it.

If you want to insert gif files, in the way other figures did, you can ditrctly write HTML code,`<figure>...</figure>` in your content, without using Hugo's cropping command.
(You can refer to `/themes/diary/layout/shortcodes/insertFigure.html`)

(Don't forget to switch on safe HTML option in config.toml)

**Comment by STYJ** [comment]
Understood! Thanks for explaining :)
