### ISSUE TITLE
仅显示主页，不显示任何文章内容

### ISSUE THREAD

**Issue by T1m3ch0** [AmazingRise/hugo-theme-diary#57]
我仅git clone 了您的theme，然后将文件夹重命名为diary，并且在hugo 的配置文件中设置theme 为diary
然后构建站点，站点不显示任何文章，这样可以说明是hugo版本不兼容吗？因为我是vercel构建的，不清楚vercel上hugo的版本是否>0.59

**Comment by Timechoo** [comment]
![image](https://user-images.githubusercontent.com/31351200/90252616-6035d480-de72-11ea-9deb-6cb69f140141.png)

**Comment by AmazingRise** [comment]
hi timecho
个人推测可能是配置文件有问题，请参照exampleSite里的config.toml，看一下少什么东西。

另外建议阅读文档后再提问，谢谢合作。

**Comment by AmazingRise** [comment]
Closed for long-time inactivity.
