### ISSUE TITLE
Question about adding custom footer

### ISSUE THREAD

**Issue by chibby0ne** [AmazingRise/hugo-theme-diary#58]
First of, I wanted to say thank you for such a great theme. I'm trying to change my current setup of Jekyll + Minima to Hugo + diary. One tiny thing I'm struggling with is that previously I was able to add a custom layout with a footer on all the pages that are blog posts. 

I was able to add a custom footer but only after creating a partial in my own repo and using it in dairy's `_default/single.html`

I'm not sure that's the best way to do that, or if there's an out-of-the-box way to do that with diary/hugo. Do you have any suggestions? Preferably I don't want to maintain my own layouts but instead use the one that comes with diary.

**Comment by AmazingRise** [comment]
Hi, chibby0ne.
You can consider appending your custom footer into `layouts/partials/copyright.html`.
The contents in it will be finally shown in the footer.

If you have further questions, please post below. Thanks.

**Comment by AmazingRise** [comment]
Closed for long-time inactivity.
