### ISSUE TITLE
Archive page not listing any posts

### ISSUE THREAD

**Issue by ric03uec** [AmazingRise/hugo-theme-diary#59]
**Describe the bug**
I've enabled `Archive` section in the sidebar using instructions in this doc: https://github.com/AmazingRise/hugo-theme-diary/wiki/Taxonomies-and-Sections-(Archive,-Categories-and-Tags)#archive-page but when navigate to the url, i get following page

![image](https://user-images.githubusercontent.com/1110988/92961378-fd5d3c00-f423-11ea-84ad-68df5e9753e1.png)

This is a brand new project I'm starting so I've set up everything from scratch. Just for testing purpose, i also added about 20 notes. All other URL's (tags, categories) work fine

**Expected behavior**
A list of old posts should be shown

**Environment**
Hugo version: ugo Static Site Generator v0.74.3-DA0437B4 linux/amd64 BuildDate: 2020-07-23T16:22:34Z
Firefox 80.0.1

Thanks in advance for the help and great work on the theme!

**Comment by AmazingRise** [comment]
Hi, ric03uec.
This seems like an issue of configuration.

- If you put your essays under `contents`, Hugo will not generate a section page for these essays.
- If you put your essays under `contents/posts`, Hugo will generate a section page at `http://url-to-your-site/posts/`.
- If you put your essays under `contents/othernames`, you can also access the page by `http://url-to-your-site/othernames/`.

So check if your contents is correctly placed under `contents/posts`. I think that's the point.

**Comment by ric03uec** [comment]
thanks @AmazingRise, that solved the issue!
