### ISSUE TITLE
发现主题在面对文章内含有一段特殊代码时会崩溃

### ISSUE THREAD

**Issue by zjh47** [AmazingRise/hugo-theme-diary#6]
你好，我发现当我在文章里面写了
````html
{{- if .Site.Params.valine}}
{{ partial "valine.html" . }}
{{- end }}
````
这样一段以后，运行`hugo server`进行预览时发现网页崩溃。chrome控制台显示![](https://cdn.jsdelivr.net/gh/zhot-cpu/PIC/20200224112919.png)
其它不包含这段代码块的网页显示都很正常。

**Comment by AmazingRise** [comment]
1. 建议你具体描述一下网页崩溃的具体现象是什么，你是在哪里添加的（哪个文件），报的什么错误。
2. 不过没关系，如果你需要添加valine的话，我已经集成了valine评论区了，启用方法请参见文档：https://github.com/AmazingRise/hugo-theme-diary/wiki/Customization#valine
3. 目前的已知bug是script出现在body中可能没法正常渲染，即整个节点会消失，但我觉得你说的不像是这个问题？（这个是Vue造成的）

**Comment by zjh47** [comment]
>建议你具体描述一下网页崩溃的具体现象是什么，你是在哪里添加的（哪个文件），报的什么错误。

这个可能是我描述的不够准确。我的意思是我在写一篇文章的时候，我写了![](https://cdn.jsdelivr.net/gh/zhot-cpu/PIC/20200224121622.png)这样一段。然后在`hugo server`预览时，我在预览网站看这篇文章的页面就变成一片白了。

>不过没关系，如果你需要添加valine的话，我已经集成了valine评论区了

谢谢！这个我在wiki页面看见了，也把valine启用成功了！👍

>目前的已知bug是script出现在body中可能没法正常渲染，即整个节点会消失

我想可能就是这个问题了😂。我把文章里面的这一段代码块删除以后，文章就是可以正常渲染的、显示的。

**Comment by AmazingRise** [comment]
1. 如果是这样的话,我觉得可能是valine.html里面的问题.不过有一说一, 相对于 Hexo , Hugo 这个模板引擎比较宽松,每个主题的配置方式都不太相同. 如果有啥问题建议多看repo里带的文档. (当然我做开发的时候也是尽量保持主题之间的一致,这样上手成本比较低,这个文档里面也有相关说明)
2. 能正常启用就好 2333
3. 至于第三点,具体的现象是添加`<script>内容</script>`之后,内容会消失,但是不会导致整篇文章渲染不正常. 这个问题先放这吧,如果还有什么很需要但是我没加进来的功能,可以提issue,我会看情况加进来的.
如果没有问题的话, 你可以关闭这个 issue 了. :)

**Comment by zjh47** [comment]
嗯，好的。我明白了。👌
