### ISSUE TITLE
Dark mode can't display normally after adding google search box 

### ISSUE THREAD

**Issue by xclwt** [AmazingRise/hugo-theme-diary#63]
just as the picture shows...
![x](https://user-images.githubusercontent.com/29428546/93115574-9fb04480-f6ee-11ea-8379-7e51e165f6d9.png)

**Comment by AmazingRise** [comment]
Fixed in https://github.com/AmazingRise/hugo-theme-diary/commit/9ed31830e9c9a923ef1bc355f167fd916a9e5c92
Thanks for your feedback.
