### ISSUE TITLE
关于资源访问的问题

### ISSUE THREAD

**Issue by opfanswyx** [AmazingRise/hugo-theme-diary#64]
![image](https://user-images.githubusercontent.com/20237214/93467132-e6d14c00-f91f-11ea-89fc-736bd6575e27.png)

您好：
我是部署在服务器nginx上的，如图所示，如果本地不挂代理的话，有字体资源访问不到的情况，该如何解决呢？

**Comment by runsisi** [comment]
this is the finial blocker for us behind the GFW :(

can we embed those resources(css/js/font) into the theme itself (yeah, no internet access needed)? @AmazingRise

**Comment by AmazingRise** [comment]
Hi, runsisi
https://github.com/AmazingRise/hugo-theme-diary/blob/9ed31830e9c9a923ef1bc355f167fd916a9e5c92/layouts/partials/head.html#L60
把这里改成SJTUG的反向代理：
```javascript
loadCSS("https://google-fonts.mirrors.sjtug.sjtu.edu.cn/css?family=Lora|Montserrat|Fira+Mono|Noto+Serif+SC|Material+Icons");
```
即可。

但是我不知道这个能稳定使用多久。

对于自行搭建Google Font的讨论，可以参考：
https://stackoverflow.com/questions/8966740/how-to-host-google-web-fonts-on-my-own-server

感谢反馈。

**Comment by runsisi** [comment]
thank you for your quick reply~ @AmazingRise 

不管是使用 sjtu 还是 ustc 得代理确实是可以解决一部分问题。

只是我个人觉得，如果能够做到尽量少（甚至没有）依赖外部资源（如 google font，bootstrap css 等）是比较完美的（特别是 google font 之类这种需要特殊访问的资源）。如果是我来实现，我可能会直接把 css/js/font 这些都当成静态资源嵌入在主题中（如果字体太大也可能根据 linux/windows/mac 不同来选择使用系统字体），这样做成一个 standalone 的站点，用户体验可能会更好，适用面可能也更广（如内网环境）。对于博客站点来说，其实引用的外部资源并不多（也不大），我个人觉得没有太大的必要引用外部资源。

当然，我主要是搞存储的，对前端开发所知甚少，如果说的不对，多多包涵 :)

**Comment by AmazingRise** [comment]
个人认为这属于一种负载均衡
如果把所有静态资源都放到服务器上，那么服务器的负担又增加了一些
不过由于特殊的环境导致Google Fonts API难以访问就是另一码事了
有问题可以继续反馈，感谢
