### ISSUE TITLE
我想自定义中间这一块的宽度，不知从何下手

### ISSUE THREAD

**Issue by FuShaoLei** [AmazingRise/hugo-theme-diary#67]
已认真看完文档及close的issues，未找到相关解答。。提issues属实无奈之举

就是这一块：
![QQ截图20210108152004](https://user-images.githubusercontent.com/33645012/103986072-049e1780-5182-11eb-9b03-6365e96050a7.png)

ps: 刚从hexo转hugo，项目结构看的有些懵逼 QAQ

**Comment by FuShaoLei** [comment]
我放弃了。。。

**Comment by runsisi** [comment]
@FuShaoLei 

https://github.com/AmazingRise/hugo-theme-diary/blob/master/assets/scss/journal.scss#L12

**Comment by FuShaoLei** [comment]
> @FuShaoLei
> 
> https://github.com/AmazingRise/hugo-theme-diary/blob/master/assets/scss/journal.scss#L12

我之前有改过这里，依然没有生效，最后发现应该要用hugo extend版本的才可以生效，我之前都是普通版本的😂
