### ISSUE TITLE
Potential bug: LiveRe comment doesn't show up

### ISSUE THREAD

**Issue by zane-ng** [AmazingRise/hugo-theme-diary#69]
**Describe the bug**
LiveRe comment area doesn't show up if set up according to tutorial.
如根据教程设置，来必力评论区不会显示。

**Expected behavior**
Should appear.
应当显示。

**Screenshots**
The problem seems to be caused by the LiveRe code being within the `$()` (as indicated in the following screenshot) in `head.html`. Removing the `$()` and leave the injection code as exampled by LiveRe will solve the issue, and the comment area will show as intended.
疑似由于来必力代码在`head.html`中被包含在`$()` 内而有此问题。移除`$()` ，使注入代码如来必力所举例，则问题解决，评论空间能够正常显示。
![image](https://user-images.githubusercontent.com/11245009/106486660-d5629800-64ec-11eb-9691-6b9fb8eabfc0.png)

**Environment**
Hugo version: 0.80.0
Deployed platform: Netlify
Browser: Chrome 88.0.4324.104

**Additional context**
Removing the LiveRe data uid info in `config.toml` will correctly remove the LiveRe comment area.
移除 `config.toml` 中的来必力 data uid 会正确地移除来必力评论区。

I have very limited coding knowledge so please correct me if I'm wrong. Thank you.
我的编程知识极其有限，故如有误还请指正。谢谢。

**Comment by AmazingRise** [comment]
Hi zane-ng:
I can't reproduce this bug in my environment.
Here is a part of config.toml:
```toml
[params]
enableLivere = true
livereId = "hellothisisatest"
```
After adding `enableLivere` and `livereId`, the comment area can be displayed normally.

So I think maybe you've missed `enableLivere`?

**Comment by zane-ng** [comment]
你好，不好意思一直忘了回复。由于个人博客停写很久，也一直没有跟进。

刚刚尝试了一下，发现由于 LiveRe 桌面端账号一直无法登录，手机端尝试登录则会出现 500 错误。建议再测试一下 LiveRe 服务稳定与可用程度，考虑从主题移除？

**Comment by AmazingRise** [comment]
没事 就放那放着吧 不好的东西不会有人用的 2333
