### ISSUE TITLE
Feature request: integrate Waline or MiniValine

### ISSUE THREAD

**Issue by zane-ng** [AmazingRise/hugo-theme-diary#70]
由于 Valine 可能存在安全风险（参照[此篇博文](https://imnerd.org/valine-may-not-so-good.html)），建议主题增加 [Waline](https://github.com/lizheming/waline) 或 [MiniValine](https://github.com/MiniValine/MiniValine) （使用 Wanline 作为后端）集成。

**Comment by AmazingRise** [comment]
Added.

https://github.com/AmazingRise/hugo-theme-diary/wiki/Comment-Area#waline
