### ISSUE TITLE
[feature] utterances integration

### ISSUE THREAD

**Issue by DreamAndDead** [AmazingRise/hugo-theme-diary#71]
[utterances](https://utteranc.es/) 相比 gitalk 更轻量，方便集成，[安全性更佳][l]

希望可以考虑集成到 diary theme 中~

[l]: https://www.xianmin.org/post/utterances-comment-system/

**Comment by ChungZH** [comment]
确实是一个很好的东西呢～ ~~（催更 逃~~

**Comment by WeepingDogel** [comment]
催更+1

**Comment by AmazingRise** [comment]
Hello everyone.
I've done this job.
You can fetch the latest code in `testing` branch.
For usage, please visit [utterances](https://github.com/AmazingRise/hugo-theme-diary/wiki/Comment#utterances) in project wiki.

If everything goes well, I would merge this feature to master.

Thanks for your support!

已经做好了,我放进了`testing`分支.用法请参见上面的链接.
如果没有问题的话,我将会把这些合并到主分支中.
感谢大家的支持!

**Comment by AmazingRise** [comment]
Merged into master.
