### ISSUE TITLE
主题如何配置 twikoo 评论系统

### ISSUE THREAD

**Issue by OldChenGit** [AmazingRise/hugo-theme-diary#72]
主题如何配置 Twikoo 评论系统！自己折腾了半天没配置好！希望大佬直接修改好，直接上环境ID即可。谢谢！😃

**Comment by ChenChilde** [comment]
![QQ截图20210228185201](https://user-images.githubusercontent.com/29373659/109415851-14094680-79f6-11eb-91ee-11798f990214.jpg)
config.toml 也开启了enabletwikoo = true
评论区显示了。但是就是无法评论和面板设置。

**Comment by ChenChilde** [comment]
最后发现目录下的journal.js禁掉就好了。但是禁掉了journal。博客无法显示白天黑夜切换按钮。错位。忘大佬修复指点下。谢谢

**Comment by tsq456** [comment]
我是从别人的hugo主题里搬来的twikoo，供你参考下，不确定能不能解决你后面的问题。

在comment.html里面加上下面这段代码：

``` html
{{- if .Site.Params.enableTwikoo -}}
<div class="pagination__title">
  <span class="pagination__title-h">欢迎评论</span>
  <hr />
</div>
  <div id="tcomment"></div>
  <script src="https://cdn.jsdelivr.net/npm/twikoo@1.2.4-beta/dist/twikoo.all.min.js"></script>
  <script>twikoo.init({ envId: 'blog-7g64ycaa61ba0fad', el: '#tcomment' })</script>
{{- end }}
```

然后在config文件里面加上下面这段代码：

```toml
[params]
enableTwikoo = true
```

希望能够解决你的问题。

**Comment by tsq456** [comment]
仔细看了下，发现你也是这代码😝，但是我这设置面板啥的是正常打开的...

**Comment by ChenChilde** [comment]
> 仔细看了下，发现你也是这代码😝、但是我这设置面板啥的是正常打开的.

我的是这样的设置的。那就奇怪了。

**Comment by tsq456** [comment]
我后来发现也是有问题，是因为作者再最外层用VUE对整个页面进行了渲染，和twikoo冲突了，导致无法使用，你把baseof里面第一层的`div = 'app' `中的=app去掉就可以正常使用了

**Comment by AmazingRise** [comment]
> 我后来发现也是有问题，是因为作者再最外层用VUE对整个页面进行了渲染，和twikoo冲突了，导致无法使用，你把baseof里面第一层的`div = 'app' `中的=app去掉就可以正常使用了

有空我打算重构一下，这个主题的代码里又有 Vue 又有 jQuery，不是很好。
不过最近实在太忙，顾不上。

如果我开工了，会在Milestone里打个标签。在此之前，也欢迎提交 Pull Request。

**Comment by tsq456** [comment]
好的，无奈本人前端苦手，只能静待大佬重构了，期待。

**Comment by OldChenGit** [comment]
大佬什么时候更新主题BUG啊！一直在期待啊！

**Comment by AmazingRise** [comment]
> 我后来发现也是有问题，是因为作者再最外层用VUE对整个页面进行了渲染，和twikoo冲突了，导致无法使用，你把baseof里面第一层的`div = 'app' `中的=app去掉就可以正常使用了

如果你仔细读源码的话，会发现我的评论功能并不是直接写在`comment.html`里的，因为`comment.html`是经过 Vue.js 渲染的。要避开 Vue.js 的话，应该把 js 代码放到`head.html`里，而把`<div>`的部分留在`comment.html`里。

要是去掉了 Vue.js 的话，这个主题也就不能用了啊 2333

**Comment by OldChenGit** [comment]
@AmazingRise 我也按照你的方法把应该把 js 代码放到head.html里 而把<div>的部分留在comment.html里。怎么还是一样的效果，
求大佬解决修复。我黑喜欢这个主题。

**Comment by AmazingRise** [comment]
试一下 twikoo 分支下的代码

https://github.com/AmazingRise/hugo-theme-diary/tree/twikoo

**Comment by AmazingRise** [comment]
Solved.
