### ISSUE TITLE
stream-container 这个容器的padding值在不同页面会有轻微变化导致页面跳动

### ISSUE THREAD

**Issue by tsq456** [AmazingRise/hugo-theme-diary#75]
stream-container 这个容器里面的左右padding值是25%，在页面宽度固定的情况下，两个页面会输出如下不同的padding数值

![](https://30924398.xyz:6001/images/2021/03/13/-1.png)

具体表现就是下图这样，可以看到明显的偏差
![](https://30924398.xyz:6001/images/2021/03/13/-2.png)
![](https://30924398.xyz:6001/images/2021/03/13/-3.png)

homepage和single都会出现偏差，但是homepage和主题自带的single页以及我自己另外建立的关于页又没有这个问题，百思不得其解是为什么。希望作者看到能解答下哈，不知道是否为BUG

备注：没有对主题进行过任何修改，并且是在hugo创建新站点后直接测试的，hugo版本是0.81。

出现问题的博客工程文件在这里：https://github.com/tsq456/testExampleBlog

**Comment by AmazingRise** [comment]
Hi tsq456,
Chrome 89.0 on Windows 10 无法复现
请提供一下具体复现环境，谢谢

**Comment by tsq456** [comment]
Chrome 版本： 88.0.4324.190（正式版本） （32 位）
Edge版本：版本 89.0.774.50 (官方内部版本) (64 位)
os：win10

均可复现此问题。

另外，我想着去别的用这个主题的博主那看看，发现这个博主[南有嘉鱼](https://blog.markhoo.com/messages/)的首页和留言板页面之间也会出现这个问题。

**Comment by tsq456** [comment]
仔细对比了下，应该是这个issue下
_Originally posted by @tsq456 in https://github.com/AmazingRise/hugo-theme-diary/issues/72#issuecomment-797872809_

我把baseof最外层的div id去掉后导致TOC相关的JS出错，然后就会出现以上问题，那就还是只能等重构框架了。

**Comment by AmazingRise** [comment]
![image](https://user-images.githubusercontent.com/8315221/111111780-e695ce80-8599-11eb-9901-25240dc27f17.png)
![image](https://user-images.githubusercontent.com/8315221/111111889-1f35a800-859a-11eb-95cc-b1596096dbad.png)
并没有成功复现

**Comment by tsq456** [comment]
是指同个站点的不同页面间，你浏览南有嘉鱼的博客的首页和留言板页没有复现这个问题吗。我发的测试站点是首页和电影之间。

如果不会的话，那就奇怪了，因为我家里和公司电脑都存在这个问题

**Comment by AmazingRise** [comment]
Closed for long-time inactivity.
