### ISSUE TITLE
Github pages 显示404因为目录底下找不到index.html

### ISSUE THREAD

**Issue by JesseStutler** [AmazingRise/hugo-theme-diary#77]
按照hugo docs中deploy到github的教程照做了：https://gohugo.io/hosting-and-deployment/hosting-on-github/ ，也成功deploy到https://jessestutler.github.io/ 了，但是显示缺少index.html。我找了一下index.html在layout文件夹里，所以我试了下直接把index.html挪到根目录底下，但是并没有像本地部署一样显示界面，而是只显示了go template。请问我是不是漏了什么步骤？本地hugo serve的话根目录是不需要生成index.html的呀，要怎么做呢？

这是我根目录底下的文件和目录：
![image](https://user-images.githubusercontent.com/38534065/113511159-fb5df480-9590-11eb-954d-feeca16df69a.png)

**Comment by JesseStutler** [comment]
仓库在https://github.com/JesseStutler/JesseStutler.github.io

**Comment by AmazingRise** [comment]
Hi JesseStutler,

1. Hugo 的本质是一个静态网页生成器，运行 `hugo` 会在 `public` 目录下生成网站；而运行 `hugo serve` 会在内存中生成网站。
> 本地hugo serve的话根目录是不需要生成index.html的呀

这是因为生成的网站文件（包括 index.html）是存在于内存中的。
将 Hugo 生成的网站部署到 GitHub 最原始的方法是：运行 `hugo`，然后将 `./public` 下的所有文件 commit 到 GitHub 上。 GitHub Action 是用来自动帮你完成这些步骤的。

2.  如果用 GitHub Action，那么它会自动从你指定的分支运行 `hugo` 命令，并把 `./public` 下生成的所有文件传到 `gh-pages` 分支下。我去看了下，你的部署是没有问题的： https://github.com/JesseStutler/JesseStutler.github.io/tree/gh-pages

问题应该出在你的设置。点这里去设置 https://github.com/JesseStutler/JesseStutler.github.io/settings
找到 GitHub Pages，把 Source 下面的 Branch 改为 `gh-pages` 应该就可以了。

**Comment by JesseStutler** [comment]
谢谢，是这样，生成了一个新分支里面有index.html，不过奇怪的是主页没样式，好像是缺少css，我看gh-pages分支里scss文件夹里是有css的，chrome的console报了这样的错：
![image](https://user-images.githubusercontent.com/38534065/113512859-411ebb00-9599-11eb-9d24-b56c06da1fe0.png)

截了一部分主页显示，不知道这是啥问题
![image](https://user-images.githubusercontent.com/38534065/113512875-58f63f00-9599-11eb-9818-ce155ec28c77.png)

**Comment by AmazingRise** [comment]
注意报错...你的 config.toml 没改好...

https://github.com/JesseStutler/JesseStutler.github.io/blob/d7b8a4e71163a0ee7d591af281e2747d8f9ff34a/config.toml#L1

**Comment by JesseStutler** [comment]
感谢感谢，第一次使用Hugo这些framework搭网站不太会用，可以正常使用了，close now
