### ISSUE TITLE
运行hugo server 报错

### ISSUE THREAD

**Issue by yangziran** [AmazingRise/hugo-theme-diary#8]
新建项目，已经将本主题下载至themes/diary目录下，根据exampleSite中的config.toml配置指定好了主题。
运行hugo server报错：
Building sites … ERROR 2020/03/08 21:39:56 Transformation failed: TOCSS: failed to transform "scss/journal.scss" (text/x-scss): this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Built in 18 ms
Error: Error building site: logged 1 error(s)

Hugo Version : Hugo Static Site Generator v0.66.0-DEV darwin/amd64 BuildDate: unknown

**Comment by AmazingRise** [comment]
报错中写到：
```
this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
```
请仔细看一下那个网址，应该是因为你的 Hugo 不是 extended 版本，不支持 scss 功能。
```
Hugo Static Site Generator v0.65.3/extended linux/amd64 BuildDate: unknown
```
具体修复方法参见那个链接，我是 Linux，不太了解 OS X 那边怎么装 `hugo-extended`，实在是爱莫能助。

**Comment by yangziran** [comment]
THK
