### ISSUE TITLE
如何创建归档页面

### ISSUE THREAD

**Issue by riba2534** [AmazingRise/hugo-theme-diary#80]
Hi，Rise

请问如何实现类似于 https://byvoid.com/zhs/blog/archive/ 这样的归档页面.

**Comment by riba2534** [comment]
猜测是，新建了一个 md 文件，手动写的？

**Comment by AmazingRise** [comment]
Hi riba2534
请参考维基页面：
Please refer to wiki:
https://github.com/AmazingRise/hugo-theme-diary/wiki/Taxonomies-and-Sections-(Archive,-Categories-and-Tags)#archive-page

**Comment by riba2534** [comment]
可能我没有说清楚，维基页面这么做只是把文章按照默认的方式展示了一遍，但是这个页面每个文章变得特别大。我理解的归档应该是只展示标题和链接，像刚才的例子那样。请问一下是通过修改模板实现，还是创建一个md文件，自己维护链接

**Comment by AmazingRise** [comment]
抱歉，我刚才没看清楚。
我不太清楚他的博客是怎么实现的，你可以问一下他。

**Comment by jossemarGT** [comment]
Hi @riba2534 did you find how to create and archive page like byvoid.com ? I am wondering how to imitate it.

**Comment by riba2534** [comment]
> Hi @riba2534 did you find how to create and archive page like byvoid.com ? I am wondering how to imitate it.

i find. you can visit blog.riba2534.cn，source in github.com/riba2534/hugo-blog
