### ISSUE TITLE
部署之后，网页格式错乱

### ISSUE THREAD

**Issue by cloud-mist** [AmazingRise/hugo-theme-diary#83]
# Q:本地预览是好的，但部署之后网页的样式错乱，如下图。
<img src="https://user-images.githubusercontent.com/49445212/116966899-bdfd9b80-ace3-11eb-80e3-e10c90f22e55.png" width=30% />

- `config.toml`中`baseURL = "http://www.shawncheung.com"`
![noplus_s](https://user-images.githubusercontent.com/49445212/116966913-c3f37c80-ace3-11eb-903e-dc581059e1d1.png)

- `config.toml`中`baseURL = "https://www.shawncheung.com"`
![pluss](https://user-images.githubusercontent.com/49445212/116966905-c0f88c00-ace3-11eb-8e9a-d01fae2b012e.png)

**不知道是什么情况，请大佬帮忙看看**😭

# config.toml
```
baseURL = "https://www.shawncheung.com"
DefaultContentLanguage = "zh-hant"
languageCode = "en-us"
title = "忆の风"
copyright = "shawn"
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4


[params]
subtitle = ""
enableGitalk = false

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"


[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/post"
name = "归档"
weight = 1
[[menu.main]]
url = "/about/index.html"
name = "关于"
weight = 4
```

**Comment by AmazingRise** [comment]
Hi, cloud-mist
请贴一下你的完整的 Hugo 版本号。
（运行`hugo version`）

**Comment by cloud-mist** [comment]
> Hi, cloud-mist
> 请贴一下你的完整的 Hugo 版本号。
> （运行`hugo version`）

`hugo v0.83.1+extended linux/amd64 BuildDate=unknown`

**Comment by AmazingRise** [comment]
或许，你把 baseUrl 里的 www 去掉试一下？

**Comment by cloud-mist** [comment]
@AmazingRise 
解决了，谢谢，打扰您了。
不过是什么原因呢? 前面在用其他主题是可以正常显示的。

**Comment by AmazingRise** [comment]
是这样的，`www`和`@`之间互相的资源请求算跨域了。
这部分的信息请参照这里： https://developer.mozilla.org/zh-CN/docs/Web/Security/Same-origin_policy 

至于你提到的其它主题，具体是哪个主题？我去看一下。

**Comment by cloud-mist** [comment]
### 其实还有点关于图片的问题。
1. `<center></center>`失效，同样`<div align="center"></div>`失效，这个主要是想让一段话或者图片居中使用。
2. 后来发现提供的`insertFigure`,可是报错，换用`Fit`也报这个错。images文件夹放在了根static下
```
{{< insertFigure
img="/images/4.png" 
caption="test" 
command="Resize" 
align="Right"
options="700x" >}}
```
```
Error: Error building site: "/home/cloudmist/study/Shawn_Blog/content/post/kindle开箱.md:34:1":   
failed to render shortcode "insertFigure": failed to process shortcode:
"/home/cloudmist/study/Shawn_Blog/themes/diary/layouts/shortcodes/insertFigure.html:20:21": execute of template failed: 
template: shortcodes/insertFigure.html:20:21: executing "shortcodes/insertFigure.html" at <$original.Resize>: nil pointer evaluating resource.Resource.Resize
```

**Comment by cloud-mist** [comment]
> 至于你提到的其它主题，具体是哪个主题？我去看一下。

这个前面在用 [even](https://github.com/olOwOlo/hugo-theme-even)  
设置：`baseURL = "http://www.shawncheung.com"`，并没有出现这个问题，我也不懂这个东西，纯粹想搞个blog记录一下学习笔记。

**Comment by AmazingRise** [comment]
> 这个前面在用 [even](https://github.com/olOwOlo/hugo-theme-even)
> 设置：`baseURL = "http://www.shawncheung.com"`，并没有出现这个问题，我也不懂这个东西，纯粹想搞个blog记录一下学习笔记。

原因是 even 并没有对 CSS 的 intergrity 进行检查。
例如这样：

```css
<link ... integrity="{{ $styles.Data.Integrity }}">
```

> ### 其实还有点关于图片的问题。
> 1. `<center></center>`失效，同样`<div align="center"></div>`失效，这个主要是想让一段话或者图片居中使用。

我这里 center 是可用的，但是要注意空行。没有空行是不行的。

```markdown
<center>

![](search_result.jpg)

</center>
```

> 后来发现提供的insertFigure,可是报错，换用Fit也报这个错。images文件夹放在了根static下

img 处要引用资源名。这个我在 [wiki](https://github.com/AmazingRise/hugo-theme-diary/wiki/Inserting-Figures) 里面写了，请务必认真阅读：

> - `img`: it must be a resource name. [How to define a source?](https://gohugo.io/content-management/page-resources/#resources-metadata-example)

感谢支持，如果有其它问题请在新的 Issue 中提出。

**Comment by cloud-mist** [comment]
好的，了解了。
`diary` 是很棒的主题，最后还是要谢谢大佬的耐心解答，非常赞。👍

**Comment by chengleqi** [comment]
我也遇到了这个问题😂

**Comment by cloud-mist** [comment]
解决了吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AmazingRise/hugo-theme-diary"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AmazingRise/hugo-theme-diary] 部署之后，网页格式错乱 (#83)





 
我也遇到了这个问题😂

**Comment by chengleqi** [comment]
> 解决了吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "AmazingRise/hugo-theme-diary" ***@***.***&gt;; 发送时间:&nbsp;2021年5月13日(星期四) 晚上8:13 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [AmazingRise/hugo-theme-diary] 部署之后，网页格式错乱 (#83) 我也遇到了这个问题😂 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

解决了，我是用GitHub Pages搞的，然后阿里云DNS CNAME过去
