### ISSUE TITLE
现在这个版本怎么打开i页面有报错，怎么修复啊~

### ISSUE THREAD

**Issue by OldChenGit** [AmazingRise/hugo-theme-diary#85]

**Comment by AmazingRise** [comment]
Hi, OldChen

不是这个版本的问题。

你的 `/static/js/journal.js` 的内容和仓库里的不太一样。

https://github.com/AmazingRise/hugo-theme-diary/blob/master/static/js/journal.js

**Comment by AmazingRise** [comment]
另外，请不要删除掉 `comment.html` 里面的作者信息。
本项目基于 MIT 协议发布，删除作者信息属于侵权行为。

**Comment by OldChenGit** [comment]
@AmazingRise 好的！感谢大佬提供的主题，并遵守作者版权！
