### ISSUE TITLE
使用Inserting-Figures的shortcode报错

### ISSUE THREAD

**Issue by chengleqi** [AmazingRise/hugo-theme-diary#88]
我想让博客中图片的位置居中并更改大小，发现正好有[inserting-Figure的shortcode](https://github.com/AmazingRise/hugo-theme-diary/wiki/Inserting-Figures)。👍
于是我在markdown文档中的metadata中添加了resources
![resource](https://user-images.githubusercontent.com/53958238/118098382-68716f00-b406-11eb-9b42-b823604537ec.png)
并在文章中引用了
![引用](https://user-images.githubusercontent.com/53958238/118098498-9191ff80-b406-11eb-8490-911f456b4f30.png)
但是没有成功，命令行终端报错：
`ERROR 2021/05/13 16:12:01 "E:\Hugo\blog\content\torrent-client.md:31:1": failed to render shortcode "insertFigure": failed to process shortcode: "E:\Hugo\blog\themes\diary\layouts\shortcodes\insertFigure.html:20:21": execute of template failed: template: shortcodes/insertFigure.html:20:21: executing "shortcodes/insertFigure.html" at <$original.Resize>: nil pointer evaluating resource.Resource.Resize`
页面报错：
![页面报错](https://user-images.githubusercontent.com/53958238/118098803-f3526980-b406-11eb-8612-52c13755b694.png)
请问一下这个是怎么回事，怎么解决。我的操作系统是Windows10，Hugo版本是hugo v0.83.1-5AFE0A57+extended windows/amd64。

ps
能问一下这个metadata中的image的tw card是干什么用的吗
![tw](https://user-images.githubusercontent.com/53958238/118098930-239a0800-b407-11eb-811a-3280fb9ca0c0.png)

**Comment by AmazingRise** [comment]
Hi chenleqi

我无法复现这个问题。经测试，当路径出问题的时候会出现这个问题。你所引用的图片，是位于`/static/torrent-client/原始bt文件.png`吗？

另外，还有一种不用定义资源的方法：在`posts`目录下新建一个文件夹，文件夹的名字为文章名，在这个目录下新建一个`index.md`，图片资源也一并放在这里。这样可以直接引用图片，不需要写 `resources`

**Comment by chengleqi** [comment]
> Hi chenleqi
> 
> 我无法复现这个问题。经测试，当路径出问题的时候会出现这个问题。你所引用的图片，是位于`/static/torrent-client/原始bt文件.png`吗？
> 
> 另外，还有一种不用定义资源的方法：在`posts`目录下新建一个文件夹，文件夹的名字为文章名，在这个目录下新建一个`index.md`，图片资源也一并放在这里。这样可以直接引用图片，不需要写 `resources`

嗯嗯 对的 图片确定是这个路径，我试试第二种方法！😃

**Comment by chengleqi** [comment]
It works! 
之前可能是路径设置错误了。。而且这第二种方法的content management也好了。
谢谢！😃
