### ISSUE TITLE
只有一篇博客，Archive栏是404 page not found，这是正常情况吗

### ISSUE THREAD

**Issue by chengleqi** [AmazingRise/hugo-theme-diary#91]
如题，先只迁移了一篇博客，Archive栏是404 page not found。
![home](https://user-images.githubusercontent.com/53958238/118109438-cbb5ce00-b413-11eb-8286-c8a74fadb808.png)
![archive](https://user-images.githubusercontent.com/53958238/118109435-c9ec0a80-b413-11eb-8b50-b718cb3b161e.png)

**Comment by AmazingRise** [comment]
Hi,
1. 请尝试将文章的 `draft` 属性设置为 `false`
2. 试一下重新运行 `hugo server`
3. 如果还是不行，请贴一下你的 `config.toml`，以及你的文章路径。

**Comment by chengleqi** [comment]
将draft 属性设置为 false后重新运行依然404.
![QQ截图20210513180340](https://user-images.githubusercontent.com/53958238/118110934-9ca05c00-b415-11eb-974b-178a88037a7e.png)
![QQ截图20210513180351](https://user-images.githubusercontent.com/53958238/118110937-9dd18900-b415-11eb-805a-d1cf4c3ed043.png)
下面是我的config.toml

`baseURL = "http://example.org/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "chengleqi's blog"
copyright = "This is a customized copyright."
theme = "diary"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "自言自语."
favicon = "/GOPHER_MIC_DROP.ico"
enableGitalk = true

enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4
`

我的文章路径是 `E:\Hugo\blog\content\Build a torrent-client by Golang\index.md`

**Comment by AmazingRise** [comment]
归档功能的本质我在这里写了: https://github.com/AmazingRise/hugo-theme-diary/wiki/Taxonomies-and-Sections-(Archive,-Categories-and-Tags)
实质上它是 Hugo 的 section 功能。
所以文章要放在 `/content/posts/`，才能在`http://yoursite/posts/`下访问到该目录下的文章归档。
当然，`posts`这个名字可以随意指定。

建议先参考 Hugo 的相关文档。

感谢反馈。

**Comment by chengleqi** [comment]
万分感谢🍭
