### ISSUE TITLE
代码高亮主题显示有问题

### ISSUE THREAD

**Issue by kands-code** [AmazingRise/hugo-theme-diary#95]
**Describe the bug**

代码高亮主题显示有问题

**To Reproduce**
Steps to reproduce the behavior.

如我的博客所见 [博客](https://qarks.top)
但我的配置是 
![图片](https://user-images.githubusercontent.com/59006329/120626884-b0c7fe00-c495-11eb-8439-e30aa8d20440.png)

**Expected behavior**

明明是亮色主题，却显示的是暗色主题

**Screenshots**

![图片](https://user-images.githubusercontent.com/59006329/120626884-b0c7fe00-c495-11eb-8439-e30aa8d20440.png)

![图片](https://user-images.githubusercontent.com/59006329/120627053-d9e88e80-c495-11eb-8633-5c4723b4f0d8.png)

**Environment**
Your Hugo version, generated from `hugo version`. hugo v0.83.1+extended linux/amd64 BuildDate=unknown
(OS information also included in hugo version, so you don't need to tell this.)
And your browser's basic information.

**Additional context**

**Comment by kands-code** [comment]
补充一个，深色模式也有问题，文字显示不清楚
![Screenshot_2021-06-03-18-11-14-970_com android browser](https://user-images.githubusercontent.com/59006329/120628338-31e9ab80-c42a-11eb-88d4-e7cf98d23413.png)

**Comment by kands-code** [comment]
还有，输入评论时会出现这样的现象
![图片](https://user-images.githubusercontent.com/59006329/120659984-75d7c180-c4b9-11eb-8b33-80aa7ffe0ea6.png)
不知道是不是正常现象

**Comment by AmazingRise** [comment]
Hi. kands-code
1. 代码高亮是由 Hugo 实现的，并不是在主题里实现的，所以请参考 Hugo 官方文档。
2. 关于 Gitalk 深色模式的问题，将会于近期修复。 可以订阅这个 issue 以跟踪进度： https://github.com/AmazingRise/hugo-theme-diary/issues/96
3. 应该是 Gitalk 本身的实现，不必担心。

最后，非常感谢你的反馈。

**Comment by kands-code** [comment]
很感谢您的回复，但是对于

>     1. 代码高亮是由 Hugo 实现的，并不是在主题里实现的，所以请参考 Hugo 官方文档。

我官方文档和dairy主题文档都有参考，但是我不论怎么修改，代码主题依旧没有变化，于是我稍微查看了一下dairy主题的css相关的代码，发现了这么一段
![图片](https://user-images.githubusercontent.com/59006329/120759480-a36a4c80-c545-11eb-9653-0e799db385e0.png)
位置在`assets/scss/journal.scss`的第128行到134行，我认为就是这一段导致了代码主题颜色一直是深色，但是我不会前端，所以我不知道该如何修改，只是猜测

请问您的测试中代码高亮能够正常设置吗？

**Comment by AmazingRise** [comment]
1. 你的猜测可以用浏览器的 F12 进行验证。代码高亮的`background`是加在`<pre>`元素上的，`<code>`的`background`被覆盖掉了。所以这些代码并不影响代码高亮。
2. 我的博客高亮主题原为 `dracula`（暗色），现在改为 `github`（亮色）
```toml
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
```

原网页：
https://amazingrise.net/posts/running-c-program-on-bare-machine/

更改后：
![image](https://user-images.githubusercontent.com/8315221/120765398-c13ab000-c54b-11eb-9158-2fcc2345ed97.png)

建议再看一下你的配置哪里有问题。

**Comment by kands-code** [comment]
好，感谢！

**Comment by kands-code** [comment]
好，感谢！
